### ISSUE TITLE
Support Skaffold namespaces

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2372] opened 2019-02-26 21:48 UTC
Skaffold CLI supports deployment and development into a custom Kubernetes namespace using `-n, --namespace string` option. If this option is set, a user can easily move his deployment into a custom namespace to avoid using default namespace or do advanced testing without touching existing and default namespaces.

This requires:
- [ ] ~~UI text field to enter custom namespace~~
- [x] UI label to display current context's namespace
- [ ] ~~saving and restoring namespace in run configuration settings~~
- [x] unit tests for run configuration settings
- [x] support for namespace option in Skaffold CLI executor and unit tests for this functionality
- [x] ability to populate ui fields from work done off the ui thread

**Comment by matthewmichihara** [comment] 2019-04-15 21:33
Gonna start taking a look at this one

**Comment by etanshaul** [comment] 2019-04-15 21:43
great. 

as we add more settings to the run configurations we should keep in mind the amount of configuration that we expose by default. Once it merits it, we can hide "advanced" configuration in a collapsible section or a separate tab. But I think with just this single added field it would fit nicely under the "Kubernetes" section now.

**Comment by matthewmichihara** [comment] 2019-04-15 21:47
true, I could see this growing out of control at some point.

**Comment by etanshaul** [comment] 2019-04-15 21:49
UXD can help here too. I've asked that we get some eyes our our new (and upcoming UIs) this quarter.

**Comment by matthewmichihara** [comment] 2019-04-15 22:13
I wonder if it'd be better to populate a combobox with valid namespaces instead of providing a free text input field. On one hand it is less error prone, but it has the potential to be slow/fail.

```
$ kubectl get namespaces
NAME                     STATUS   AGE
alice                    Active   103d
bob                      Active   103d
default                  Active   103d
kube-public              Active   103d
kube-system              Active   103d
michihara                Active   31m
```

**Comment by etanshaul** [comment] 2019-04-15 22:16
I assume the skaffold command doesn't support creating the namespace on the fly if it doesn't exist right? 

Also how much slower is the namespace listing execution than the cluster listing - I was out during the review of that PR, so I'm wondering how we handed any latency there in the UI? I assume were not blocking the UI thread.

**Comment by matthewmichihara** [comment] 2019-04-15 22:36
AFAIK, skaffold can't do that. If I try to supply it with something like `skaffold deploy  --namespace namespace-that-doesnt-exist` it doesn't create it, and it fails.

Cluster listing is fast and does not look like it needs to talk to the cluster. Namespace listing does need to talk to the cluster (so subject to network delays). I've seen it take over 1s.

In the current implementation of the cluster listing, it is just done on the UI thread. We could improve that code and this code with [this mechanism that @ivanporty mentioned](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/46#discussion_r274984322). If we do want to go down this path, I can add loading these things off the UI thread as another subtask of this issue as well.

**Comment by etanshaul** [comment] 2019-04-15 23:00
oh I see. 

Probably doing an incremental PR here of just adding a freeform field, only to update it later to use a combobox wouldn't be of much value. And I do think having the dropdown is preferred. So that being said, offloading from the UI thread does seem to be a prereq of this.

**Comment by ivanporty** [comment] 2019-04-16 15:33
We can start with a editable combo box and treat it as a free form field for now for simplicity, then it's going to be easy to switch to actually showing current namespaces for the current active cluster too. UI background method Kotlin way is coming!

**Comment by matthewmichihara** [comment] 2019-04-16 15:35
thanks @ivanporty!

**Comment by matthewmichihara** [comment] 2019-04-17 19:24
Current plan for the namespace editable combobox:
![image](https://user-images.githubusercontent.com/79073/56315013-aebf4b80-6124-11e9-9457-e7ee9e20ddea.png)

Unrelated, but I was thinking of renaming the `Cluster name:` label to just `Cluster:`. Thoughts?

**Comment by etanshaul** [comment] 2019-04-17 19:24
+1 to changing it to just `Cluster:`
And looks great otherwise.

**Comment by matthewmichihara** [comment] 2019-04-17 19:49
One complication is that items in this combobox are going to be dependent on the currently selected cluster.

I think I'll need some kind of `KubectlApi` method that lets me specify the cluster I want to run a command in so that I can ask for the namespaces for a particular cluster. Something that produces: `kubectl --context <selected cluster> get namespaces`. Does that sound reasonable?

**Comment by matthewmichihara** [comment] 2019-04-17 20:46
Looking a little more into this, I just realized that I'd been conflating `cluster` and `context` :facepalm:. The default kubeconfig contexts from docker-for-desktop and GKE create contexts that have the same name as the cluster, but that isn't always the case as some of the examples here illustrate: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/.

1. Which would be more useful to show in the run config UI, the context or the cluster? We currently show the context, even though it is mislabelled as `Cluster: `.
2. Contexts can have configured namespaces that `kubectl` commands are performed in. If we do want to show the current context, what should the expected behavior be if we let the user select a namespace? Override what is in the context configuration? I assume that's what Skaffold does.

**Comment by etanshaul** [comment] 2019-04-17 21:19
I was under the impression that we want to show the context. The context as I understand it essentially will define the target of deployment. If we showed the cluster, what would it mean then for the user to switch to a different one?

for (2) can we check to see what Skaffold does in this case?

**Comment by matthewmichihara** [comment] 2019-04-17 21:28
If skaffold is provided a namespace, it will override whatever is set in the context configuration.

Hm yeah I think context is the right thing to show. I should rename `Cluster: ` to `Context: `.

I'm thinking this namespace combobox will just map 1:1 with skaffold `--namespace` flag, so we won't try to do things like pre-select a namespace in the context configuration.

**Comment by matthewmichihara** [comment] 2019-04-18 23:09
We decided offline to just show the namespace associated with a selected context in the run configuration screen instead of letting the user select a namespace.

However, I now wonder if we should just try to align with what VS Code is doing, which is to surface the active namespace in the Cluster Explorer, and allow changing a context's namespace there (via the `Set as Active Namespace` command). This modifies the kubeconfig setting, and does not use the skaffold --namespace flag at all. Thoughts @etanshaul @ivanporty ?

**Comment by etanshaul** [comment] 2019-04-19 01:39
Are both of these options mutually exclusive? 

Although I do think displaying the namespace in the run config is relatively low priority. And +1 to being able to change namespace via the explorer once it’s in place.

**Comment by matthewmichihara** [comment] 2019-04-19 14:26
You're right, they are not mutually exclusive. Ok let's give it a shot! As a dependency to this, I think I'll need a `kubectl config view` equivalent `KubectlApi` method in order to get the namespace for a context. I'm happy to take a stab at creating this, unless @ZariaHoward you had plans to create something similar.

**Comment by etanshaul** [comment] 2019-04-19 14:34
I think @ZariaHoward is working on log streaming so I’d say feel free to give it a go!

**Comment by matthewmichihara** [comment] 2019-04-22 19:40
With https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/72 landing, I think we're done here, since we decided to not really support Skaffold namespaces. We good to close this @ivanporty ?

**Comment by ivanporty** [comment] 2019-04-22 20:19
Yep, let's go with cluster explorer view, it feels more natural.

**Closed** 2019-04-22 20:27 UTC
Labels: Good first issue, Kubernetes

**Comment by dwctua** [comment] 2020-07-25 22:15
I think this field is very useful, the point is to lock down the name space so it won't be impacted if context or namesapce changed. the explorer view won't help much here. As FYI, openshift has strict permission and user may not have enough access to browse the namespaces at all. 
However, it is not necessary to be a combo box. a plain text field is good enough
