### ISSUE TITLE
Unable to read file from WEB-INF folder

### ISSUE THREAD

**Issue by achecinski** [GoogleCloudPlatform/cloud-code-intellij#1705] opened 2017-10-20 14:27 UTC
I have the following facet config for an appengine module :

<facet type="web" name="Web">
      <configuration>
        <descriptors>
          <deploymentDescriptor name="web.xml" url="file://$MODULE_DIR$/src/main/webapp/WEB-INF/web.xml" />
        </descriptors>
        <webroots>
          <root url="file://$MODULE_DIR$/src/main/webapp/info" relative="public-root/info" />
          <root url="file://$MODULE_DIR$/docs/ui" relative="public-root/apidocs" />
          <root url="file://$MODULE_DIR$/src/main/webapp" relative="/" />
          <root url="file://$MODULE_DIR$/target/backend/WEB-INF" relative="WEB-INF" />
        </webroots>
      </configuration>
    </facet>

I have a file in the WEB-INF folder that I try to read by doing new File("WEB-INF/filename").
When running in terminal with mvn appengine:devserver everything works fine.
But when running debug in Intellij, I get a FileNotFoundException.
I checked the file is copied to the target dir.
This is a maven project and the facet is automatically generated by importing the maven project.
(I had it working before upgrading from appengine plugin to google cloud tools)

I have already reinstalled Intellij, removed the .idea and .iml files and reloaded the project. Nothing seems to work.

I have made a test. I have remove the logging.properties file from the target WEB-FOLDER folder (/project-dir/module-dir/target/module-name/WEB-INF).
When I run the module, I get a FileNotFoundException for logging.properties. Meaning the this is the actual folder from which the webResources are loaded.
The file I'm trying to read is in the same target folder and I'm not able to read it.

I have added the following debug code :

System.out.println("########### " + new File("WEB-INF").getAbsolutePath());

When run from withing Intellij I get :
/Applications/IntelliJ IDEA.app/Contents/bin/WEB-INF

When run from my terminal (mvn appengine:devserver), I get :
/Users/userName/Documents/workspace/projectName/moduleName/target/backend/WEB-INF (I changed folder names to generic once for confidentiality).

The code comes from another child module of the same project and it is added as a maven dependency in my module. But I have the same issue add the code to module I'm running.

**Comment by achecinski** [comment] 2017-10-20 14:32
The workaround for now is to run the mvn appengine:devserver from the terminal and remote debug from intellij. But this is not the most efficient solution.

**Comment by achecinski** [comment] 2017-10-20 14:43
I rolled back from google cloud tools to google app engine integration.
This works, but It's a pity I can not use the new Google Cloud Tools and benefit from it's features.

**Comment by chanseokoh** [comment] 2017-10-20 15:03
Do you see the following warning when running in IntelliJ?

`WARNING: Your working directory, (...) is not equal to your web application root (...)`

If so, I believe you can make it run if IntelliJ has a way to set a working directory when launching the server. @etanshaul or @patflynn can help here.

Some references:
   - https://stackoverflow.com/questions/43618900/cannot-access-file-using-relative-path-in-local-test-when-developing-google-app
   - https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1932#issuecomment-306194400

Better yet, it's better not to use `File()` IMO: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1932#issuecomment-306193843

**Comment by chanseokoh** [comment] 2017-10-20 15:07
> Better yet, I recommend not using File() in this way IMO: GoogleCloudPlatform/google-cloud-eclipse#1932 (comment)

I believe you'll be able to load files as classpath resources.

**Comment by chanseokoh** [comment] 2017-10-20 15:14
Oh, I think I see an issue in your case. You are running multiple modules (services), right? By its design limitation, the dev_appserver1 cannot emulate the production env precisely with respect to working directories when having multiple modules. That is, the dev_appserver1 has no choice but to use a single working directory for all modules, as it emulates the services inside a single JVM.

https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/411#issuecomment-300885234

**Comment by chanseokoh** [comment] 2017-10-20 15:21
In summary,

1. By looking at `/Applications/IntelliJ IDEA.app/Contents/bin/WEB-INF`, a working directory is not set when running inside IntelliJ.
   - I believe it should be automatically set it in a single module case. Since you are running multiple modules, we are not setting it automatically.
1. _If IntelliJ has a way to set a working directory_, you can do so as a workaround.
   - However, this directory will function as a working directory for all modules, which does not reflect the production env. You should be cautious when taking this workaround to debug and test locally.
1. Considering all these, I think the best approach is to migrate such `new File()` uses and load files as classpath resources.

**Comment by etanshaul** [comment] 2017-10-20 17:39
thanks @chanseokoh for the investigation. 

@achecinski let us know if you've had any luck with the suggestions - loading the files as classpath resources instead.

**Comment by achecinski** [comment] 2017-10-23 12:05
Thanks guys for your answer.
I try your solutions and let you know if I manage to make it work.
FIY, I have multiple modules in my project, some of them are services but I'm trying to run a single one. It does not depend on other services.
I just needs files from another module which get properly copied by a maven directive.

**Comment by achecinski** [comment] 2017-10-23 14:42
I have the message : 
Your working directory, (/Applications/IntelliJ IDEA.app/Contents/bin) is not equal to your 
web application root
I'd very much like to use classPath resources instead of new File(), but there is some code that I can't change for now.
If I can not change the working directory, I will have to use the old appengine plugin instead of google cloud tools.

**Comment by chanseokoh** [comment] 2017-10-23 14:58
Fair enough. For now, the only way you can have a correct working directory that will work as you want is to run a single module locally.

Also, don't forget the old appengine plugin may, though unconfirmed, force setting the working directory of an arbitrary module (possibly a root module) for all modules when running locally — the old plugin uses the same dev_appserver1 that the new plugin uses. The actual production env is different in this regard, so make sure you understand the consequences.

**Comment by chanseokoh** [comment] 2017-11-06 22:27
Another workaround is to go into the built webapp directory that you are interested in (e.g., `target/your-artifact-final-name-1.0-SNAPSHOT/`) and do `mvn -f ../../pom.xml appengine:run`. The working directory of the dev appserver will be then that webapp directory. Not sure if there is any pitfall in this way though.

**Comment by jmah-cc** [comment] 2020-06-11 16:10
Bulk closing issues older than 2 years. Feel free to re-open if this issue is still repro'ing or important.

**Closed by jmah-cc** 2020-06-11 16:10 UTC
Labels: area/app-engine, kind/user-reported
