### ISSUE TITLE
installing the latest version of the cloud code plugin with Gemini code assist features disables intellij's own full line code completion

### ISSUE THREAD

**Issue by karahatherly** [GoogleCloudPlatform/cloud-code-intellij#3215] opened 2024-06-30 23:59 UTC
### Expected Behavior
Disabling the gemini feature in the cloud code plugin's settings should re-enable intellij's full line code completion.

### Actual Behavior
Having the cloud code plugin installed disables intellij's full line code completion, regardless of the cloud code plugin's settings.

### Additional Information
I don't want gemini running over my code and I don't want its suggestions, I just want to keep using the cloud code plugin the way I always have without it interfering with my usage of intellij and its own features. Disabling gemini should re-enable intellij's own code completion, and if that's a limitation of the intellij plugin framework then gemini code assist should be its own plugin, separate to cloud code.

**Comment by ivanporty** [comment] 2024-08-13 22:59
The new version (24.8.1) should not conflict with the full line completion, but it will take some time for Jetbrains to unmark the plugin as conflicting. We'll update you once it's done.

**Comment by ivanporty** [comment] 2024-08-16 23:32
Duplicate of #3189

**Closed as completed by ivanporty** 2024-08-16 23:32 UTC
Labels: area/ai
