### ISSUE TITLE
Cannot hide the Cloud Code sidebar.

### ISSUE THREAD

**Issue by iosifnicolae2** [GoogleCloudPlatform/cloud-code-intellij#3113] opened 2022-10-29 20:49 UTC
(Please ensure you are running the latest version of Cloud Code for IntelliJ with _Help > Check for Updates_)
- Cloud Code for IntelliJ version: 22.10.1-222
- Google Cloud SDK version: 407.0.0
- OS: Mac OS X 13.0

**What did you do?**
Click on the `Hide` button.

**What did you expect to see?**
I was expecting the sidebar to be hidden.

**What did you see instead?**
The sidebar is not hidden.
<img width="1844" alt="image" src="https://user-images.githubusercontent.com/7108834/198851796-a5da3738-0578-4063-afe2-2a163a0276eb.png">

**Comment by etanshaul** [comment] 2022-10-31 16:16
@iosifnicolae2 thanks for the report. We are aware of this bug and are looking into it.

**Comment by peterlin741** [comment] 2022-12-08 20:09
This was caused by a [platform issue](https://youtrack.jetbrains.com/issue/WEB-56864/Hide-Button-on-Debugger-not-functioning-when-the-Debugger-Console-tab-is-focused) and was fixed in `IntelliJ 2022.3.1`

**Closed by peterlin741** 2022-12-08 20:09 UTC
