### ISSUE TITLE
run cloud code  kubernates  gets stuck with no response in different states

### ISSUE THREAD

**Issue by mhmd-khalil49** [GoogleCloudPlatform/cloud-code-intellij#2963] opened 2021-07-18 10:44 UTC
I've installed the latest version (21.6.1) of cloud code Kubernetes in IntelliJ IDE version "11.0.9" to try to debug Skaffold environment remotely . I configured the task and  when I clicked on the icon to run debugging skaffold it shows the command below and stops.

C:\Users\Mohamed\AppData\Local\cloud-code\bin\versions\aa\skaffold.exe debug --filename authentication-deploy.yaml --label ide=Idea --label ideVersion=2020.3.1.0.0 --label ijPluginVersion=unknown --rpc-port 50051 --port-forward=true --wait-for-deletions-max=2m0s --status-check=true --enable-rpc=true --verbosity info

(screenshots are often helpful)

### Actual Behavior
![image](https://user-images.githubusercontent.com/58072664/126064080-f483e139-cc82-4721-9d4a-4e13d06b506d.png)

### Additional Information

- IDE type (. IntelliJ, Pycharm):IntelliJ
- IDE version:11.0.9
- Cloud Code version (Settings > Plugins > Cloud Code): 21.6.1
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: yes
  - Version of the Cloud SDK:348.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v1.127.0
- Operating System:windows 10

**Comment by etanshaul** [comment] 2021-07-19 18:40
hi @mhmd-khalil49 thanks for posting the issue. 

Am I correct in understanding that the session just gets stuck in that state shown in the screenshot? Does it consistently get stuck (does it ever work)?

And a couple more questions to possibly help debug:

- can you try running the command that is printed `C:\ .... skaffold.exe debug ...` directly in a terminal to see if it also gets stuck that way (to help rule out an IDE interaction)
- what runtime is your application using (Java, Python etc. )?

**Comment by mhmd-khalil49** [comment] 2021-07-28 14:03
Thanks, Etan for your reply

yes, it always gets stuck in different states (start deploying, checking
cache,..) and never ever complete deploying, regards to runtime, it is Java
"1.8.0_271".

I ran the printed command in cmd, and the same it gets stuck in checking
cache as below image

[image: image.png]

**Comment by mhmd-khalil49** [comment] 2021-07-28 14:04
Thanks, Etan for your reply

yes, it always gets stuck in different states (start deploying, checking cache,..) and never ever complete deploying, regards to runtime, it is Java "1.8.0_271".

I ran the printed command in cmd, and the same it gets stuck in "**checking cache**"  as below image

![image](https://user-images.githubusercontent.com/58072664/127336076-7b36762a-05a3-4b8d-bea8-3f3cbc9c9b31.png)

**Comment by etanshaul** [comment] 2021-07-28 14:27
Thanks. There _might_ bit more info to help us debug if you set logging verbosity to `DEBUG` (for both IDE runs, and command line runs).

To set it for the IDE:
Set the verbosity in the run config under `advanced`
<img width="662" alt="Screen Shot 2021-07-28 at 10 23 35 AM" src="https://user-images.githubusercontent.com/1735744/127339742-70d6c1a4-e859-4592-965c-908ab9ccc7b9.png">

To set it for the CLI:
Just add `--verbosity debug` to the `skaffold` command

**Comment by mhmd-khalil49** [comment] 2021-07-28 16:46
I set the log level to debug, it gets stuck in the same step starting deploy
![image](https://user-images.githubusercontent.com/58072664/127362911-dbd43148-0b2d-4c28-9e6d-407dbacd6846.png)

**Comment by etanshaul** [comment] 2021-07-28 16:51
cc @briandealwis from the skaffold side

**Comment by mhmd-khalil49** [comment] 2021-07-29 13:35
I am trying multiple times after minimizing the path of workspace location to be root drive, but still gets stuck on Starting deploy

![image](https://user-images.githubusercontent.com/58072664/127501416-3c27d323-907e-40f0-8694-9b7a95a2f6c4.png)

**Comment by briandealwis** [comment] 2021-07-30 00:16
`kubectl version —client` doesn’t contact your cluster and so should report the same values. The passing errors from `unknown` indicates pretty clearly  that Cloud Code is picking up a different kubectl than your command window. 

Have you configured Cloud Code to use a manual dependency? Might be worth searching your hard drive for `kubectl.exe` executables.

**Comment by mhmd-khalil49** [comment] 2021-07-30 12:10
I already found kubectl.exe in windows PATH related to Docker, so I removed it from PATH, then the command ran successfully as below screen, but unfortunately deploying did not complete as usual. I hope you can figure out where is the problem. @briandealwis 

![image](https://user-images.githubusercontent.com/58072664/127650723-d65e6e0e-9cff-4617-b1c5-20902817c2f7.png)

**Comment by briandealwis** [comment] 2021-07-30 17:59
That `exporting metrics` happens at the very end of the Skaffold execution: you can see a similar message in your previous posts.

But this is baffling as with DEBUG, Skaffold should be showing the output of the `kubectl create --dry-run` command, exactly as is shown with the `kubectl version` command.

Could you try running that `kubectl create --dry-run=client` command from the command line?

It sounds silly, but have you tried rebooting your machine?  It's sad, but <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Del</kbd> has cured many a problem with Windows…

**Comment by mhmd-khalil49** [comment] 2021-07-31 13:46
thanks for your support, but  I removed kubectl from widows PATH that made first conflicts with version, so such command "kubectl create --dry-run" won't be recognized from cmd. I already rebooted my machine multiple times.

**Comment by briandealwis** [comment] 2021-08-01 03:24
Cloud Code provides its own copy of `kubectl`: you should find it somewhere under `c:\Users\Mohamed\AppData\Local\cloud-code`.  This kubectl should normally have been picked up and used by Cloud Code.

**Comment by mhmd-khalil49** [comment] 2021-08-02 11:08
I have configured Cloud Code to use a manual dependency which worked fine after that, but still, it is baffling and silly that why Cloud Code doesn't work with their own dependencies.

**Comment by etanshaul** [comment] 2021-08-02 14:54
> I have configured Cloud Code to use a manual dependency which worked fine after that, but still, it is baffling and silly that why Cloud Code doesn't work with their own dependencies.

Agreed that this is baffling. One option you could try is deleting the cloud-code managed dependency directory and trying again, in case something got corrupted.

1) Configure Cloud Code to `manage and install CLI dependencies` in Settings:
<img width="819" alt="Screen Shot 2021-08-02 at 10 53 23 AM" src="https://user-images.githubusercontent.com/1735744/127881244-4a014034-b2a7-4bf9-a755-08fbef8cfd91.png">

2) Delete the managed Cloud Code directory under your home directory followed by `AppData\Local\cloud-code`

3) Restart the IDE so that Cloud Code initiates a reinstall of the managed dependencies.

After (3), and the install completes, if you could also share a screen of the dependency settings page. Thanks.

**Comment by mhmd-khalil49** [comment] 2021-08-02 16:44
thanks @etanshaul ,do you mean delete whole folder of cloud code or just delete bin folder inside as below image?

![image](https://user-images.githubusercontent.com/58072664/127895751-288d6150-1f59-46eb-9df4-393403f5391b.png)

**Comment by etanshaul** [comment] 2021-08-02 16:47
> thanks @etanshaul ,do you mean delete whole folder of cloud code or just delete bin folder inside as below image?

The whole folder. Cloud Code will recreate it after restarting the IDE if `allow the plugin to manage and install CLI dependencies` is selected.

**Comment by mhmd-khalil49** [comment] 2021-08-02 19:06
I deleted the whole folder and already started IDE which downloaded the folder again, and during follow-up messages, I noticed installed minikube , however it is not showing dependencies as below image.

![image](https://user-images.githubusercontent.com/58072664/127911034-413d8799-415d-412b-9cb8-b04f89d16cc1.png)

**Comment by etanshaul** [comment] 2021-08-02 19:09
@mhmd-khalil49 you've discovered an oddity that `minikube` is actually managed separately by the Cloud SDK. If you have the setting (at the top of that page) configured to use a Cloud SDK on your system, instead of letting Cloud Code manage it, this will happen (you can install minikube in your custom gcloud by running `gcloud components install minikube`). We will be cleaning this up soon.

Did wiping out the folder help fix the skaffold session issue by any chance?

**Comment by mhmd-khalil49** [comment] 2021-08-02 19:26
no, it still gets stuck in deployinh.

![image](https://user-images.githubusercontent.com/58072664/127913088-822790c3-fa27-4826-9ea6-f7a474cf95a5.png)

**Comment by etanshaul** [comment] 2021-08-02 19:37
I see. One more thing we can try (thanks for the patience):

1) Open up the Cloud Code terminal (which automatically paths in Cloud Code's dependencies, so you can interact with them): Tools > Cloud Code > Cloud Code terminal:
<img width="748" alt="Screen Shot 2021-08-02 at 3 35 46 PM" src="https://user-images.githubusercontent.com/1735744/127914116-29d6701b-2aa2-4150-8c3f-fc5a32284233.png">

2) try running some kubectl commands to see if things return as expected (or if they hang):
`kubectl version`
`kubectl get pods`

**Comment by mhmd-khalil49** [comment] 2021-08-05 15:21
the commands work fine, anyway I configured cloud code dependencies to use my custom path of Skaffold, Kubectl, miniKube

**Comment by etanshaul** [comment] 2021-08-05 16:56
thanks for trying. sorry we still aren't at the bottom of this. I'll keep open to track - if any new insight comes in please share. we'll also keep an eye on this behavior.

**Comment by etanshaul** [comment] 2021-11-03 20:47
@mhmd-khalil49 are you still running into this by any chance? We have been unable to reproduce.

**Comment by emmanuelbaah** [comment] 2022-02-08 16:06
@mhmd-khalil49 gentle ping to ask if you are still encountering this issue

**Comment by peterlin741** [comment] 2022-05-16 17:43
Closing this. Feel free to comment and we can reopen if you run into further issues.

**Closed by peterlin741** 2022-05-16 17:43 UTC
Labels: kind/bug, area/kubernetes, area/skaffold, priority/p2
