### ISSUE TITLE
intellij “Failed to enable GCP auth addon”

### ISSUE THREAD

**Issue by Max-kilzieh** [GoogleCloudPlatform/cloud-code-intellij#2949] opened 2021-06-28 22:48 UTC
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior
The Java Cloud Run Helllo Word sample to work after installing Docker and running Cloud Run: Run Locally

### Actual Behavior
I receive the following error:

> Enabling GCP auth addon...
> 
> Failed to enable GCP auth addon. Deployment will continue but GCP credentials will not be added to minikube. Please ensure 
> you have up to date application default credentials (ADC) by running `gcloud auth login --update-adc
 `
<img width="1817" alt="Screenshot 2021-06-29 004541" src="https://user-images.githubusercontent.com/54858105/123712841-70308a00-d873-11eb-99e3-8215e58990fe.png">

Things that I have tried and didn't solve the problem

- run `gcloud auth login --update-adc`
- use a different service account
- not provide a service account
-  provide the environment variable `GOOGLE_APPLICATION_CREDENTIALS`

### Additional Information

- IDE type: IntelliJ IDEA
- IDE version: IntelliJ  2021.1.2 (Ultimate Edition)
Build #IU-211.7442.40, built on June 1, 2021

- Cloud Code version (Settings > Plugins > Cloud Code): 21.5.1
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK:  Yes
  - Version of the Cloud SDK: 346.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v1.25.0 not using Kubernetes features
- Operating System: Windows 10 10.0

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by sivakku** [comment] 2021-06-28 22:57
Similar to https://github.com/kubernetes/minikube/issues/11565 On the vscode side that was closed out https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/441.

**Comment by Max-kilzieh** [comment] 2021-06-28 23:46
Installing `minikube` and following this comment fixed this issue https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/441#issuecomment-867216616

**Comment by etanshaul** [comment] 2021-06-30 15:08
thanks for the update @Max-kilzieh we will look into a fix so that the workaround you mentioned won't be required

**Comment by ProbStub** [comment] 2021-07-23 08:24
> thanks for the update @Max-kilzieh we will look into a fix so that the workaround you mentioned won't be required

This is rather annoying actually and I am facing the same issue. Is there any ETA already for a fix?

**Comment by etanshaul** [comment] 2021-07-23 16:15
@ProbStub re-opening since you are still facing this issue. We'll sync up with the minikube team to investigate.

cc @medyagh @sharifelgamal

**Comment by medyagh** [comment] 2021-07-23 21:21
Hi there,

@etanshaul @ProbStub @Max-kilzieh @sivakku 

we have a [PR](https://github.com/kubernetes/minikube/pull/11945) that might fix this issue, do you mind giving the binary in this PR a try to see if that fixes the problem ?

https://storage.googleapis.com/minikube-builds/11945/minikube-linux-amd64 
https://storage.googleapis.com/minikube-builds/11945/minikube-darwin-amd64 
https://storage.googleapis.com/minikube-builds/11945/minikube-windows-amd64.exe

**Comment by etanshaul** [comment] 2021-08-19 17:03
hey @medyagh sorry for the delay on this. We are triaging this and will try out your fix and confirm. Thanks.

**Comment by ProbStub** [comment] 2021-08-19 18:25
@medyagh apologies just seeing this and will give it a run on Sunday and report back.

**Comment by matthewmichihara** [comment] 2021-08-30 16:26
Will try to confirm this week.

**Comment by matthewmichihara** [comment] 2021-08-31 22:40
hey @medyagh sorry for the delay.

I tried the mac minikube binary you posted and it didn't seem to fix the issue. The issue is intermittent so I tested this by starting and stopping the Cloud Run Local Development session in Cloud Code a few times. It failed once out of the 5 or so times I ran it.

Cloud Code logs:
```
Validating Docker settings...
Preparing Google Cloud SDK (this may take several minutes for first time setup)...

Initializing Minikube. Minikube may take several minutes to initialize for the first time...

Checking status of cloud-run-dev-internal Minikube cluster...
Status of Minikube api-server is RUNNING
Enabling GCP auth addon...

Failed to enable GCP auth addon. Deployment will continue but GCP credentials will not be added to minikube. Please ensure you have up to date application default credentials (ADC) by running `gcloud auth login --update-adc`

Starting the Cloud Run development session...
skaffold dev --filename /var/folders/0v/z39yp43116ld73b7d51tsgnc00m1zt/T/cloud-code-temp-skaffold13877666566489161510.tmp --rpc-port 50051 --skip-tests=true --port-forward=true --enable-rpc=true --kube-context cloud-run-dev-internal --minikube-profile cloud-run-dev-internal
Listing files to watch...
 - untitled64
Generating tags...
 - untitled64 -> untitled64:latest
Checking cache...
 - untitled64: Found Locally
Tags used in deployment:
 - untitled64 -> untitled64:fe7cafd76c0ea5337ed0d9bc6cd1bf77b808056a1e712a8f709257847a7ae32b
Starting deploy...
Cleaning up...
time="2021-08-31T18:25:46-04:00" level=warning msg="deployer cleanup:kubectl create: running [kubectl --context cloud-run-dev-internal create --dry-run=client -oyaml -f /var/folders/0v/z39yp43116ld73b7d51tsgnc00m1zt/T/cloud-code-temp-k8s15284436286033595052.tmp]
 - stdout: \"\"
 - stderr: \"Unable to connect to the server: net/http: TLS handshake timeout\
\"
 - cause: exit status 1" subtask=-1 task=DevLoop
Deploy Failed. Could not connect to cluster due to "https://127.0.0.1:58819/version?timeout=32s": net/http: TLS handshake timeout. Check if minikube is running using "minikube status -p cloud-run-dev-internal" command and try again.

Failed to start Cloud Run dev session.
```

And here are the minikube logs: https://gist.github.com/matthewmichihara/13cd0ceb88768cc71015b58a59e51e36

Anything else you recommend I try?

**Comment by etanshaul** [comment] 2021-09-13 15:38
@medyagh any thoughts on this?

**Comment by sharifelgamal** [comment] 2021-09-13 19:55
I have couple more GCP changes coming down the pipe in the 1.23.1 release, I'm hoping htat will straighten some of these issues out.

I would also suggest just trying the 1.23.0 minikube binary to see if it helps, I'm pretty sure I made changes after that PR was merged.

**Comment by matthewmichihara** [comment] 2021-09-13 20:13
@sharifelgamal ok cool, when are you folks planning on shipping 1.23.1?

**Comment by sharifelgamal** [comment] 2021-09-13 20:14
In the next couple of days

**Comment by matthewmichihara** [comment] 2021-09-16 18:23
It looks like this is fixed now by minikube 1.23.0. I just tried a bunch of test runs with the Go and Java Cloud Run samples and can no longer reproduce issues with the gcp-auth addon failing to be enabled.

I'm using Cloud Code 21.9.2 allowing the plugin to manage dependencies (minikube 1.23.0).
![image](https://user-images.githubusercontent.com/79073/133664766-770d5b1e-0045-4f32-84bf-68492b8e46ce.png)

**Comment by ProbStub** [comment] 2021-09-17 09:45
I am sorry for the delayed response. I am holding for 1.23.1 to try again but with the following setup the auth issue seems to persist:    
- minikube version: v1.23.0
- Google Cloud SDK 357.0.0 (shows minikube 1.21.0??)

Even though there is an authenticated account:
`
opssandbox % gcloud auth list
 Credentialed Accounts
ACTIVE  ACCOUNT
*       <account>@gmail.com
`
And existing containers
`
opssandbox % gcloud container images list
$NAME
gcr.io/<project-id>/sparkk8
`
A simple spark image would not load and fail.
`
opssandbox % spark-submit --master k8s://https://127.0.0.1:53940 \
> --deploy-mode cluster \
> --name spark-pi \
> --class org.apache.spark.examples.SparkPi \
> --conf spark.executor.instances=2 \
> --conf spark.kubernetes.container.image=gcr.io/<project-id>/sparkk8  \
> local:///opt/spark/examples/jars/spark-examples_2.12-3.1.2.jar 10000000
`
More specifically fail with an authentication issue
`
opssandbox % kubectl describe pods spark-pi-5e847e7bf2f6b5e5-driver
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  50s                default-scheduler  Successfully assigned default/spark-pi-5e847e7bf2f6b5e5-driver to minikube
  Normal   BackOff    19s (x2 over 49s)  kubelet            Back-off pulling image "gcr.io/reactsandbox-93690/sparkk8"
  Warning  Failed     19s (x2 over 49s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    5s (x3 over 50s)   kubelet            Pulling image "gcr.io/reactsandbox-93690/sparkk8"
  Warning  Failed     4s (x3 over 49s)   kubelet            Failed to pull image "gcr.io/reactsandbox-93690/sparkk8": rpc error: code = Unknown desc = Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
  Warning  Failed     4s (x3 over 49s)   kubelet            Error: ErrImagePull

`

**Comment by matthewmichihara** [comment] 2021-09-17 14:21
@ProbStub A few questions:
- Are you running this all through Cloud Code's Cloud Run run configuration in IntelliJ?
- Does what you're trying to do work from the command line?
- Can you share what your Preferences -> Tools -> Cloud Code -> Dependencies screen looks like?

**Comment by briandealwis** [comment] 2021-09-17 21:13
@ProbStub a few other questions:
- you didn't redact the project ID in your events show that the cluster is trying to pull from gcr.io/reactsandbox-xxx — is that the project hosting your cluster?
- does `kubectl get secrets` show a `gcp-auth` secret of type `kubernetes.io/dockercfg`?

**Comment by ProbStub** [comment] 2021-09-18 06:55
@matthewmichihara 
1. Yes all of the above has been performed inside a Cloud Code Terminal on PyCharm (not IntelliJ)
2. Actually it doesn't work on a regular terminal either, that is why I was hoping for the plugin in the first place
3. Screenshot [PyCharmPreferences.pdf](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/7189379/PyCharmPreferences.pdf)

@briandealwis 
1. Thanks. Redacted now. It's the project hosting the images, I am stuck at the local minikube cluster deployment. I have no issues accessing GCP hosted clusters.
2. The minikube context does not have a gcp-auth secret at all

Is the missing secret the key to this?

**Comment by briandealwis** [comment] 2021-09-18 11:41
Yes, this missing secret is the key: it configured a registry pull secret so that the cluster can access private images. gcp-auth does require that you have a default GCP project configured though (@matthewmichihara the IDEs pass the project along, right?).

Could you do the following:
1. Let’s try clearing out the current minikube instance: `minikube delete -p cloud-run-dev-internal`
2. Check if you have a default GCP project configured by running: `gcloud config get-value project`
3. If unset then run: `gcloud config set project <project-id>`
2. Start minikube:`minikube start -p cloud-run-dev-internal`
3. Enable gcp-auth but with full logging.  `minikube addons enable gcp-auth -p cloud-run-dev-internal —logtostderr -v5`
4. If the previous command was successful 🤞 then run `kubectl get secrets —context cloud-run-dev-internal`

And please include the output here.

**Comment by ProbStub** [comment] 2021-09-18 18:49
@briandealwis all done on a PyCharm Cloud Code Terminal (there was some action on a few other contexts while I ran this  but trust that it would not have interfered):
1. Let’s try clearing out the current minikube instance:
``% minikube delete -p cloud-run-dev-internal``
``🙄  "cloud-run-dev-internal" profile does not exist, trying anyways.``
``💀  Removed all traces of the "cloud-run-dev-internal" cluster.``
2. Check default GCP project id (it's the same as the GCR for images): 
 ``% gcloud config get-value project``
``PROJECTID-XXXX``
3. Re-set default GCP project id (just in case):
`` % gcloud config set project reactsandbox-93690``
``Updated property [core/project].``
4. Start minikube:
 ``% minikube start -p cloud-run-dev-internal``
``😄  [cloud-run-dev-internal] minikube v1.23.0 on Darwin 11.5.2``
``   ▪ MINIKUBE_ACTIVE_DOCKERD=minikube``
``✨  Automatically selected the docker driver. Other choices: virtualbox, ssh``
``👍  Starting control plane node cloud-run-dev-internal in cluster cloud-run-dev-internal``
``🚜  Pulling base image ...``
``💾  Downloading Kubernetes v1.22.1 preload ...``
``    > preloaded-images-k8s-v12-v1...: 515.04 MiB / 515.04 MiB  100.00% 68.79 Mi``
``    > gcr.io/k8s-minikube/kicbase: 355.82 MiB / 355.82 MiB  100.00% 17.78 MiB p``
``🔥  Creating docker container (CPUs=2, Memory=3886MB) ...``
``🐳  Preparing Kubernetes v1.22.1 on Docker 20.10.8 ...``
``    ▪ Generating certificates and keys ...``
``    ▪ Booting up control plane ...``
``    ▪ Configuring RBAC rules ...``
``🔎  Verifying Kubernetes components...``
``    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5``
``🌟  Enabled addons: storage-provisioner, default-storageclass``
``❗  /Users/USERNAME/Library/Application Support/cloud-code/bin/versions/3042a5cc5a82983fd9c0fcf810045e877c423285d704dc3f69ce8d75ed4733be/kubectl is version 1.19.12, which may have incompatibilites with Kubernetes 1.22.1.``
``    ▪ Want kubectl v1.22.1? Try 'minikube kubectl -- get pods -A'``
``🏄  Done! kubectl is now configured to use "cloud-run-dev-internal" cluster and "default" namespace by default``
5. gcp-auth with loging:
``  % minikube addons enable gcp-auth -p cloud-run-dev-internal —logtostderr -v5`` 
`` ❌  Exiting due to MK_USAGE: usage: minikube addons enable ADDON_NAME`` 
6. Get secrets - did not execute due to add on error

**Comment by briandealwis** [comment] 2021-09-18 21:52
🤦 the logging failed as my browser helpfully rewrote the double-dash as an em-dash!

One hypothesis is that you’re encountering the problem I too encountered in https://github.com/kubernetes/minikube/issues/12481: that there are some leftover gcp-auth objects that are preventing the re-enablement of gcp-auth.

If you encounter this problem again, could you tell us what you see with `kubectl get all --context cloud-run-dev-internal -n gcp-auth`? And then try running from the command-line `kubectl delete ns/gcp-auth --context cloud-run-dev-internal` to remove all traces of gcp-auth, and then retry launching from Cloud Code. 

I am a bit puzzled as to why you didn’t have a `cloud-run-dev-internal` profile though.

**Comment by matthewmichihara** [comment] 2021-09-20 14:47
The original issue here is about gcp-auth failing to enable when using Cloud Code's Cloud Run local development run configuration:

![image](https://user-images.githubusercontent.com/79073/134020556-42837f8a-962d-4ffb-952d-36554e1d00e6.png)

@ProbStub It sounds like you've been using the Cloud Code terminal.

Can you confirm that the above run configuration does not work for you? 
Can you post the logs that appear in the run output logs when you run this run configuration?

**Comment by matthewmichihara** [comment] 2021-10-04 16:14
@ProbStub @briandealwis Going to close this out. Please open a new issue if you continue to run into problems.

**Closed by matthewmichihara** 2021-10-04 16:14 UTC
Labels: kind/bug, priority/p1, area/cloud-run, area/minikube

**Comment by austintraver** [comment] 2023-02-23 06:07
> Could you do the following:
> 
> 1. Let’s try clearing out the current minikube instance: `minikube delete -p cloud-run-dev-internal`
> 
> 2. Check if you have a default GCP project configured by running: `gcloud config get-value project`
> 
> 3. If unset then run: `gcloud config set project <project-id>`
> 
> 4. Start minikube:`minikube start -p cloud-run-dev-internal`
> 
> 5. Enable gcp-auth but with full logging.  `minikube addons enable gcp-auth -p cloud-run-dev-internal —logtostderr -v5`
> 
> 6. If the previous command was successful 🤞 then run `kubectl get secrets —context cloud-run-dev-internal`
> 
> 
> And please include the output here.

Thank you for posting this. In 2023, two years after this issue first cropped up, I was using Cloud Code within my IDE, and attempts to run my Cloud Run instance locally would hang with the following message:

> Enabling GCP auth addon...
>
> Failed to enable GCP auth addon. Deployment will continue but GCP credentials will not be added to minikube. Please ensure you have up to date application default credentials (ADC) by running `gcloud auth login --update-adc`

Following these steps fixed my issue.
