### ISSUE TITLE
Support for Java 11 App Engine Standard Runtime

### ISSUE THREAD

**Issue by gbouras** [GoogleCloudPlatform/cloud-code-intellij#2782] opened 2020-06-12 21:18 UTC
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version:
- OS: Mac osx 10.16
IntelliJ 2020

**What did you do?**
Just went to cloud run - appengine support and tried to add appengine standard support

**What did you expect to see?**

**What did you see instead?**
There was an error generating the appengine-web.xml file for App Engine standard support. Some operations such as deploy and local-run may not work properly.  Please try again or generate the file manually in the WEB-INF directory of your module's web resource directory.  If you are using Maven or Gradle, make sure to first sync the project with IDEA by pressing refresh in the corresponding tool window.

(screenshots are helpful)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment] 2020-06-12 21:23
Thanks @gbouras for filing this. To help us debug, could you please provide some info about your project structure:

- Are you in Ultimate or Community Edition of the IDE?
- Maven or Gradle?
- Are you using Java 8 (the App Engine integration supports only Java 8 atm; we have an open issue to improve the messaging here)?
- The java 8 runtime only supports WAR based builds. Is this consistent with your project? (e.g. not a fat-jar like a typical Spring-boot app)

Thanks!

**Comment by etanshaul** [comment] 2020-06-12 21:28
@gbouras We are currently discussing this internally so I don't want to promise you that feature prematurely. 

If it's ok with you I will rename this issue to be something around requesting Java 11 App Engine Runtime support and we'll keep it open to track.

I'll keep this updated with any developments too.

**Comment by gbouras** [comment] 2020-06-12 21:30
Yes please do, I appreciate it and I hope you have a good weekend!

**Comment by etanshaul** [comment] 2020-06-12 21:35
You too! don't hesitate to reach out for any other feature requests or bugs you run into.

**Comment by jmah-cc** [comment] 2020-12-03 16:57
@gbouras We're prioritizing other features over AppEngine currently. I've added this to our backlog and keeping this issue open so other users can upvote this.

**Comment by jmah-cc** [comment] 2020-12-03 16:57
Closing as a dupe of #2665

**Closed by jmah-cc** 2020-12-03 16:57 UTC
Labels: area/app-engine, kind/feature-request
