### ISSUE TITLE
LanguageServerProjectComponent uses Disposed Project

### ISSUE THREAD

**Issue by fsladkey** [GoogleCloudPlatform/cloud-code-intellij#2728] opened 2020-03-24 14:45 UTC
```
java.lang.AssertionError at ComponentManagerImpl.lambda$throwAlreadyDisposed$1 : Already disposed: Project (Disposed)
```

Stacktrace
```
java.lang.AssertionError: Already disposed: Project
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$0(ComponentManagerImpl.java:153)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:825)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:71)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:64)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:151)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:144)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:286)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at com.google.cloud.tools.intellij.languageclient.ClientStateHolder$Companion.instance(ClientStateHolder.kt:41)
	at com.google.cloud.tools.intellij.languageclient.YamlEditorWatcher.<init>(YamlEditorWatcher.kt:50)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent$setupServer$2.invokeSuspend(LanguageServerProjectComponent.kt:103)
	at (Coroutine boundary.()
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent$projectOpened$1.invokeSuspend(LanguageServerProjectComponent.kt:130)
Caused by: java.lang.AssertionError: Already disposed: Project 
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$0(ComponentManagerImpl.java:153)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:825)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:71)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:64)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:151)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:144)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:286)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at com.google.cloud.tools.intellij.languageclient.ClientStateHolder$Companion.instance(ClientStateHolder.kt:41)
	at com.google.cloud.tools.intellij.languageclient.YamlEditorWatcher.<init>(YamlEditorWatcher.kt:50)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent$setupServer$2.invokeSuspend(LanguageServerProjectComponent.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by peterlin741** [comment] 2020-08-04 22:21
Duplicate of https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/1571

**Closed by peterlin741** 2020-08-04 22:21 UTC
Labels: area/lsp, kind/crash-report, priority/p2
