### ISSUE TITLE
Cannot find file by /schemas/*.json

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2565] opened 2019-05-20 14:20 UTC
```
java.lang.Throwable: Cannot find file by /schemas/v1beta9.json
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.jetbrains.jsonSchema.extension.JsonSchemaProviderFactory.getResourceFile(JsonSchemaProviderFactory.java:37)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.editing.SkaffoldSchemaFileProvider.getSchemaFile(SkaffoldSchemaFileProvider.kt:46)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getSchemaForProvider(JsonSchemaServiceImpl.java:551)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.access$700(JsonSchemaServiceImpl.java:37)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState.createFileProviderMap(JsonSchemaServiceImpl.java:525)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState.access$500(JsonSchemaServiceImpl.java:455)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.compute(JsonSchemaServiceImpl.java:468)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.compute(JsonSchemaServiceImpl.java:464)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:48)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.getValue(JsonSchemaServiceImpl.java:476)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.getValue(JsonSchemaServiceImpl.java:464)
```

IntelliJ 2019.1.2
Plugin 19.5.2

This is odd because the schema file was added prior to the 19.5.2 release

**Comment by etanshaul** [comment] 2019-05-20 14:38
I can't reproduce this. All the schema files are in place. Tested on osx and linux.

@GoogleCloudPlatform/cloud-tools-for-intellij anyone else notice this? If not, I'll close

**Comment by matthewmichihara** [comment] 2019-05-20 14:40
Would this be something that shows up in the event log? I've never seen it.

**Comment by etanshaul** [comment] 2019-05-20 14:49
This came via a user reported error. So in other words, an uncaught exception.

**Comment by etanshaul** [comment] 2019-05-23 15:38
we are getting some user reports about this. I've seen various IDEs, like CLion, RubyMine.

Do you mind investigating? At a minimum I think we can handle the exception more gracefully (and just not load the schema) instead of allowing it to throw an IDE exception.

**Comment by etanshaul** [comment] 2019-05-23 15:39
@matthewmichihara, sorry - meant to direct the question above to you

**Comment by etanshaul** [comment] 2019-05-31 15:30
@matthewmichihara any findings on this? (we haven't seen the error report in a while)

**Comment by matthewmichihara** [comment] 2019-06-03 13:46
Haven't had a chance to take a look, will investigate today.

**Comment by matthewmichihara** [comment] 2019-06-03 18:15
I've been playing around with a [hello world ruby project](https://github.com/matthewmichihara/ruby-sinatra-skaffold) and also am unable to reproduce this in RubyMine. I'm inclined to say we should just close and re-open if it happens a lot more.

**Comment by matthewmichihara** [comment] 2019-06-04 21:45
Closing

**Comment by sageprice** [comment] 2019-06-10 14:38
Looks like we got another similar report this morning -- this time in PyCharm 2019.1.3 looking for v10 on Windows 10. Copying error here:

```
java.lang.Throwable: Cannot find file by /schemas/v1beta10.json
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.jetbrains.jsonSchema.extension.JsonSchemaProviderFactory.getResourceFile(JsonSchemaProviderFactory.java:37)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.editing.SkaffoldSchemaFileProvider.getSchemaFile(SkaffoldSchemaFileProvider.kt:46)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getSchemaForProvider(JsonSchemaServiceImpl.java:551)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.access$700(JsonSchemaServiceImpl.java:37)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState.createFileProviderMap(JsonSchemaServiceImpl.java:525)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState.access$500(JsonSchemaServiceImpl.java:455)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.compute(JsonSchemaServiceImpl.java:468)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.compute(JsonSchemaServiceImpl.java:464)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:48)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.getValue(JsonSchemaServiceImpl.java:476)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.getValue(JsonSchemaServiceImpl.java:464)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState.getFiles(JsonSchemaServiceImpl.java:498)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.isMappedSchema(JsonSchemaServiceImpl.java:344)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.isMappedSchema(JsonSchemaServiceImpl.java:340)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.isSchemaFile(JsonSchemaServiceImpl.java:328)
	at com.jetbrains.jsonSchema.ide.JsonSchemaService.isSchemaFile(JsonSchemaService.java:30)
	at com.jetbrains.jsonSchema.JsonSchemaIconProvider.getIcon(JsonSchemaIconProvider.java:35)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:104)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$2(ElementBase.java:100)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:100)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:44)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:280)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:165)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:121)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:89)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:164)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Product details:
```
app.name.version
 PyCharm
app.version.major
 2019
app.version.minor
 1.3
java.version
 11.0.2
java.vm.vendor
 JetBrains s.r.o
os.name
 Windows 10
plugin.version
 19.5.3
```

Re-opening to track.

**Closed** 2019-06-18 16:27 UTC
Labels: Kubernetes, editing, user reported
