### ISSUE TITLE
Cannot use service account when running Cloud Run deployment locally

### ISSUE THREAD

**Issue by vstokarev** [GoogleCloudPlatform/cloud-code-intellij#2940] opened 2021-06-01 23:37 UTC
- Cloud Code for IntelliJ version: 21.5.1
- Google Cloud SDK version: 342.0.0
- OS: Mac OS X 11.3.1

I'm trying to get secrets in Secret Manager from an application running in local Cloud Run deployment. It works only the first time I run the app, but then it resets credentials if I make any changes to the code. I'm using PyCharm version 2021.1.1.

**What did you do?**
1. Create a new project using starting template https://cloud.google.com/code/docs/intellij/creating-a-cloud-run-app.
2. Go to Run -> Edit Configurations... Select Cloud Run: Run Locally. Expand Advanced Revision Settings and specify a service account in "Service Account:" field.
3. In requirements.txt add 
```
google-cloud-secret-manager==2.4.0
```
4. In app.py update `hello()` function:

```python
def hello():
    """Get Cloud Run environment variables."""
    service = os.environ.get('K_SERVICE', 'Unknown service')
    revision = os.environ.get('K_REVISION', 'Unknown revision')

    client = secretmanager.SecretManagerServiceClient()

    response = client.access_secret_version(
        name="projects/PROJECT_ID/secrets/SECRET_NAME/versions/1")
    payload = response.payload.data.decode("UTF-8")

    return render_template('index.html',
        message=payload,
        Service=service,
        Revision=revision)
```
(need to replace PROJECT_ID and SECRET_NAME with actual values)

5. Run the app.
6. Open http://127.0.0.1:8080 and make sure you see welcome page with your secret value in header.
7. In `app.py` change something (e.g. edit any comment) and save changes. Cloud Code will rebuild the container and run it.

**What did you expect to see?**
Welcome page with secret value in header every time I reload it or change the code.

**What did you see instead?**
I only get secret value once - after the first run. When I make any changes in the code and save them - it looses service account credentials. After rebuilding the container and calling this endpoint again I get "Internal Server Error" and the following error in console:

```
google.api_core.exceptions.PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projects/PROJECT_ID/secrets/SECRET_NAME/versions/1' (or it may not exist).
```

which means that after the first launch it uses service account credentials, but after the reload it falls back to ADC. My user account does not have access to the secret, so I get 403 Permission denied error.

**Comment by matthewmichihara** [comment] 2021-06-02 14:45
Thank you for the detailed report. I am able to reproduce this as well, we will take a look.

**Comment by matthewmichihara** [comment] 2021-06-02 16:07
When I disable the minikube gcp-auth plugin, I stop seeing this issue, so I think there's some kind of conflict between the credentials set by `gcloud alpha code export --service-account ...` and minikube. I filed https://github.com/kubernetes/minikube/issues/11563 to see if a fix can be made there.

**Comment by axmerc** [comment] 2021-06-14 17:54
Our friends on minikube are working on this!

**Comment by etanshaul** [comment] 2021-06-21 16:19
minikube team is still working this

**Comment by briandealwis** [comment] 2021-06-23 14:18
@sharifelgamal confirmed that the fix is live in the gcp-auth-webhook image and will be in the next release of minikube.   You can try out the fixed gcp-auth with:

    minikube addons enable gcp-auth --images="GCPAuthWebhook=k8s-minikube/gcp-auth-webhook:v0.0.6"

**Comment by matthewmichihara** [comment] 2021-06-28 16:13
This looks like the fix will be included in the minikube 1.22.0 release. Will keep this open until gcloud includes this minikube version.

**Comment by vstokarev** [comment] 2021-07-02 22:43
@briandealwis how can I apply gcp-auth update to managed minikube? If I run the suggested command it tries to update system minikube (which is stopped by default).

**Comment by vstokarev** [comment] 2021-07-08 18:47
minikube 1.22.0 has been released.

**Comment by matthewmichihara** [comment] 2021-07-12 19:37
@vstokarev Managed minikube should be automatically updated in the next gcloud release.

**Comment by matthewmichihara** [comment] 2021-07-20 15:24
Still waiting on minikube 1.22.0 to make it into gcloud to mark this as closed. Gcloud 349.0.0 is still on minikube 1.21.0.

**Comment by matthewmichihara** [comment] 2021-07-27 21:14
Sorry, still waiting on minikube 1.22.0 to make it into gcloud. I'm told it has been submitted and will be in the next release.

**Closed** 2021-08-03 19:47 UTC
Labels: area/cloud-run, area/secret-manager, kind/bug, priority/p1
