### ISSUE TITLE
Streaming logs on pods with more than one container

### ISSUE THREAD

**Issue by davidjayb** [GoogleCloudPlatform/cloud-code-intellij#2657] opened 2019-10-08 18:10 UTC
- Cloud Code for IntelliJ version: 19.9.2
- OS: Mac OSX

**What did you do?**
Select the "Stream logs" option for a Pod

**What did you expect to see?**
Log output for all containers or a way to specify the appropriate container

**What did you see instead?**
The following error message from the server:

> \<directory>/kubectl logs -f pods/\<pod name> --namespace \<namespace>
> Error from server (BadRequest): a container name must be specified for pod \<pod name>, choose one of: [<container 1> <container 2> <container 3>]

**Comment by etanshaul** [comment] 2019-10-08 18:14
hey @davidjayb . thanks for using Cloud Code!

We are aware of this and it will be fixed in the next release 19.10.1, going out later today.

In this update, we'll have the ability to display all containers of a given pod, and stream logs directly from them. From our staged release notes:

19.10.1 - Latest Release
This release fixes several bugs and improves stability of the Cloud Code plugin. It also contains enhancements to the Kubernetes Cluster Browser, including the ability to view containers in your pods and stream logs from them.

New Features
You can now drill down into your pods to view your containers. Stream logs directly from a running container.
cluster browser
New option to pin your Kubernetes deployments to whatever is set as your system-wide current context.
cluster browser
Copy Kubernetes resource names to the clipboard by right-clicking on a node in the Kubernetes Cluster Browser.
Refresh any Kubernetes resource individually to update its state.
Bug Fixes
Fixes a NPE caused by Maven-aware code for displaying a notification suggesting Spring Cloud GCP for Spring projects using GCP APIs.
Fixes an issue where the Cloud Code dependency installer could be stuck in a broken state, blocking Kubernetes deployments and debugging.
Fixed an exception that could occur during LSP initialization due to invalid document listener state.

**Comment by davidjayb** [comment] 2019-10-08 18:17
@etanshaul that's great to hear and thanks for the quick feedback.

**Comment by etanshaul** [comment] 2019-10-08 19:20
19.10.1 just went out, so it should start showing up in the plugin repo soon.

I'll close this issue for now. Feel free to check back here if you have any more questions or issues. Thanks again.

**Closed by etanshaul** 2019-10-08 19:20 UTC
Labels: Kubernetes, feature request, user reported
