### ISSUE TITLE
"Deployed Resources" view does not display deployments to non-default namespaces

### ISSUE THREAD

**Issue by dallasvaughan** [GoogleCloudPlatform/cloud-code-intellij#3099] opened 2022-09-21 18:26 UTC
### Expected Behavior
"Deployed Resources" shows resources related to the namespace(s) being deployed to according to the Skaffold configuration (or default to showing all namespaces)

### Actual Behavior
"Deployed Resources" only shows resources deployed to the `default` namespace.

### Additional Information

- IDE type: IntelliJ IDEA Ultimate
- IDE version: 2022.2.2
- Cloud Code version (Settings > Plugins > Cloud Code): 22.9.2-221-IB.1
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: 402.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v1.39.2
- Operating System: macOS 12.5.1

**Comment by ivanporty** [comment] 2022-09-26 19:29
Thanks for the report @dallasvaughan! This seems to be a bug on our side, we should be checking for a namespace in the context used for deployments. We'll evaluate this and get back to you about further steps or plans.

**Comment by ivanporty** [comment] 2022-10-12 19:14
The current design of the display resources UI element is to only display resources in the current context, and a single namespace associated with this context. If the context is using a non-default namespace, the display resources shows the deployment for this different namespace (as shown in this screenshot, namespace name is `development`):

<img width="493" alt="Tue Oct 11 2022 15_34_29 GMT-0700 (Pacific Daylight Time)" src="https://user-images.githubusercontent.com/11686100/195428463-9d50b5a3-e742-417a-9710-f81cf7c479b4.png">

We don't display *deployed* resources across multiple namespaces as this would make deployment window resource intensive and a bit heavy on UI, but you can always use Kubernetes Explorer to watch resource changes for other namespaces or even other clusters if you need to - the explorer supports viewing and updating all namespaces and clusters regardless of the current context.

Please let us know if that makes sense @dallasvaughan

**Comment by dallasvaughan** [comment] 2022-10-12 19:26
Makes sense! Thanks for looking into this.

**Comment by ivanporty** [comment] 2022-10-12 20:02
Thanks @dallasvaughan! Closing for now - working as designed. Let us know if you can use the explorer successfully for your multi-namespaces deployments.

**Closed by ivanporty** 2022-10-12 20:02 UTC
Labels: area/kubernetes
