### ISSUE TITLE
IDE Becomes unresponsive when connecting to a Cloud SQL database.

### ISSUE THREAD

**Issue by francescortiz** [GoogleCloudPlatform/cloud-code-intellij#3169] opened 2023-10-30 10:27 UTC
### Expected Behavior

When I a open a Cloud SQL connection the IDE shouldn't freeze.

### Actual Behavior

When I open a Cloud SQL connection, as soon as I go to the Database explorer the IDE freezes. 

### Additional Information

- IDE type: IntellIJ and DataGrip
- IDE version: Happened for serveral versions. Currently IntelliJ 2023.2.4
- Cloud Code version: Several, currently 23.10.1-api-version-222 
- Cloud SDK:
  - Are you allowing the plugin to manage the Cloud SDK: Yes: 452.0.1
- Operating System: macOS Sonoma 14.0

### Workaround

If I copy/paste the command that cloud sql runs into a terminal, even into the IDE terminal, then the database explorer works like charm. It is only when the plugin initiates the `cloud-sql-proxy` command that the IDE hangs.

**Comment by ivanporty** [comment] 2023-10-30 15:51
Thanks @francescortiz! Your report seems similar to #3168, we are looking into it.

**Comment by ivanporty** [comment] 2023-10-30 15:55
It seems like we cannot reproduce easily. Is there anything specific about your database setup? ideally, we would like to take a look at IDE log file to look for any errors (idea.log, find using Help -> Show Log In Finder menu)

**Comment by ivanporty** [comment] 2023-12-07 00:05
Closing in favor of newer #3173

**Closed as completed by ivanporty** 2023-12-07 00:05 UTC
Labels: area/databases
