### ISSUE TITLE
Profile not loaded in cloude code run configuration

### ISSUE THREAD

**Issue by wollowizard** [GoogleCloudPlatform/cloud-code-intellij#3091] opened 2022-08-23 09:44 UTC
Here's a video of the issue:

https://user-images.githubusercontent.com/2480280/186126634-96348274-e68e-4906-a69f-cb72fad0a14e.mov

And the code to reproduces:
[profile-not-loaded.zip](https://github.com/GoogleCloudPlatform/cloud-code-intellij/files/9401396/profile-not-loaded.zip)

### Expected Behavior
I create a run configuration and choose a profile. I save the run configuration. I open again the run configuration and the profile is gone.

### Additional Information
The run configuration xml contains
```
<option name="skaffoldProfile" value="personal" />
```
and when running, the correct profile is selected. So I believe it's just a UI issue

- IDE type (e.g. IntelliJ, Pycharm): **IntelliJ IDEA 2022.2.1 (Ultimate Edition)** 
- IDE version: **Build #IU-222.3739.54, built on August 16, 2022**
- Cloud Code version (Settings > Plugins > Cloud Code): **22.8.1-221-IB.1**
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: **Yes**
  - Version of the Cloud SDK: **398.0.0**
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): **v1.39.1**
- Operating System: **macOS Monterey v12.5.1**

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by cmeury** [comment] 2022-08-29 07:18
Encountered this as well, it really seems to be only a UI issue.

**Comment by peterlin741** [comment] 2022-08-29 14:49
The team is aware of this issue and will look into it

**Comment by ivanporty** [comment] 2023-02-10 17:04
duplicate of #3118, please follow discussion there.

**Closed by ivanporty** 2023-02-10 17:04 UTC
