### ISSUE TITLE
Provision to pass skaffold -v=debug flag 

### ISSUE THREAD

**Issue by prary** [GoogleCloudPlatform/cloud-code-intellij#2630] opened 2019-08-12 10:25 UTC
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: 2018.2.2.0.0 
- OS: Windows

**What did you do?**
In kuberntes continous deploy there text box is missing where user can specify skaffold flags like -v=debug to see debug logs of skaffold
**What did you expect to see?**
there should be text box where user can specify skaffold flags like -v=debug to see debug logs of skaffold

**Comment by ivanporty** [comment] 2019-08-12 14:28
@sageprice could you please confirm if we support this (`verbosity`) Skaffold option via an environment variable, or it's a special one without such support?

**Comment by etanshaul** [comment] 2019-08-12 14:32
I was told by Skaffold that _all_ flags are supported via env vars as well (its baked in to the architecture).

**Comment by sageprice** [comment] 2019-08-12 14:48
Etan's comment matches my understanding. The gotcha is that Skaffold has slightly different names for setting env variables and flags -- I believe the equivalent for `-v=debug` would be `SKAFFOLD_VERBOSITY=debug` if I'm reading https://skaffold.dev/docs/references/cli/ correctly.

**Comment by sageprice** [comment] 2019-08-12 14:52
Minor correction -- debug doesn't look like a valid value for `-v`. The docs say: 

```
-v, --verbosity LOG-LEVEL | Uses a specific log level. Available log levels are info, warn, error, fatal. Default value is warn.
```

Not sure about the debug value being passed here, though it's entirely possible I'm misreading. @prary could you please clarify if you're looking to run skaffold in debug mode, or if this is a logging setting?

**Comment by prary** [comment] 2019-08-13 10:29
@sageprice  I use -v=debug mode to see verbose mode

**Comment by prary** [comment] 2019-08-13 10:30
> I was told by Skaffold that _all_ flags are supported via env vars as well (its baked in to the architecture).

Everytime you don't want to set the environment variable and unset them as well

**Comment by sageprice** [comment] 2019-08-13 14:10
Thanks for sending that PR to skaffold! Wasn't aware of the alternative `debug` value.

> > I was told by Skaffold that _all_ flags are supported via env vars as well (its baked in to the architecture).
> 
> Everytime you don't want to set the environment variable and unset them as well

That's totally reasonable. It is fair to say that we're still trying to figure out exactly how we want to surface skaffold options in run configurations -- we'd rather not overwhelm by presenting every flag as a toggle in the run configs. We appreciate the good feedback that log verbosity is a priority.

In the meantime, if you want to set this env variable only for one Cloud Code run config, we do have the option to supply custom env variables in the run config editor. That way you can make run configs for each flag configuration you want. For example:

![env_vars](https://user-images.githubusercontent.com/9577120/62948507-78cc6400-bdb2-11e9-81c9-966a45d33cfc.png)

Does that work for now?

**Comment by prary** [comment] 2019-08-13 16:20
Hi, this should work but for me somehow it is not able to find kubectl in path(which is in the path) and not allowing me to save the env variable hence I am not able to apply the changes. Will debug and verify the same.


So my suggestion world be give normal text field where user can directly put all the argument, that will eradicate dependency on skaffold otherwise every time something changes in skaffold you will need to update the same. Input field for the argument along with environment variable would give the best UX

**Comment by etanshaul** [comment] 2019-08-13 16:22
hi @prary 

Could you post a screenshot of the error you are seeing please? 

Also, what OS are you running - is it Linux by any chance? If so, there is a known issue in linux - when the IDE is launched from GUI then its not able to access the shell environment (and therefore may be complaining the `kubectl` is not available on the path). A quick workaround is instead to launch IntelliJ from the terminal.

**Comment by etanshaul** [comment] 2019-08-13 16:24
> So my suggestion world be give normal text field where user can directly put all the argument, that will eradicate dependency on skaffold otherwise every time something changes in skaffold you will need to update the same. Input field for the argument along with environment variable would give the best UX

Thanks for the suggestion! We are considering doing this. We want to have a balance between configuration flexibility and easy of use.

**Comment by prary** [comment] 2019-08-17 04:42
https://photos.app.goo.gl/PJi7uZkZgGU9mJBb7

OS windows

**Comment by prary** [comment] 2019-08-17 04:54
I am facing very strange issue apart from this, when I run from GUI i.e Kubenetes continous deploy DEBUG mode then it fails at image building step but when I copy same command and run in separate terminal then it runs successfully. Any idea whats happening wrong?

**Comment by etanshaul** [comment] 2019-08-17 15:03
Hi @prary

Could you please show some snippets of the failure you are seeing when running in debug mode? Including the command that is being executed (it should be printed at the top of the console output). You can manually remove any identifying information.

Also since you are able to run Continuous Deploy (debug mode) now I assume you got past the missing kubectl issue? (Otherwise I’m not sure how you managed to execute the run config).

**Comment by prary** [comment] 2019-08-18 12:50
Hi @etanshaul kubectl error still persist but i am able to run debug mode through GUI. Ran it today debug mode ran fine but I am not getting the option to put breakpoint. 
Command it executed 

C:\Users\prashant\go\src\github.com\GoogleContainerTools\skaffold.exe debug --filename java-hello-world/skaffold.yaml --label ide=idea --label ideVersion=2019.1.3.0.0 --label ijPluginVersion=unknown --port-forward=true

**Comment by prary** [comment] 2019-08-18 12:52
https://photos.app.goo.gl/9QbtJt5f5HtjL3jW9

**Comment by ivanporty** [comment] 2019-08-19 13:54
@prary what is the output in the IDE `Event Log` window (lower right corner of the project window usually)? Does it show debug port number (5005), any other port forwards? What is the version of skaffold you are using?

**Comment by prary** [comment] 2019-08-19 15:20
Following are logs in event log window, I have tried same with 34, 35 and 36 version

> 8/18/2019
> 6:01 PM	IDE and Plugin Updates: IntelliJ IDEA is ready to update.
> 
> 6:02 PM	Managed Google Cloud SDK: Managed Google Cloud SDK installation failed: java.nio.file.FileSystemException: C:\Users\prashant\AppData\Local\google\ct4j-cloud-sdk\LATEST: failed to delete one or more files; see suppressed exceptions for details.
> 
> 6:02 PM	Dockerfile detection
> 				You may setup Docker deployment run configuration for the following file(s): 
> 				java-guestbook\backend\Dockerfile
> 				java-guestbook\frontend\Dockerfile
> 				java-hello-world\Dockerfile
> 				Disable this notification (show balloon)
> 
> 6:04 PM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@asiapac.ad.jpmorganchase.com
> 
> 6:45 PM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@asiapac.ad.jpmorganchase.com
> 
> 8/19/2019
> 9:52 AM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@asiapac.ad.jpmorganchase.com
> 
> 10:31 AM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@asiapac.ad.jpmorganchase.com
> 
> 10:35 AM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@asiapac.ad.jpmorganchase.com
> 
> 12:04 PM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@asiapac.ad.jpmorganchase.com

**Comment by prary** [comment] 2019-08-19 15:22
Tried with skaffold version 34, 35 and 36

Logs from event log window
> 8/18/2019
> 6:01 PM	IDE and Plugin Updates: IntelliJ IDEA is ready to update.
> 
> 6:02 PM	Managed Google Cloud SDK: Managed Google Cloud SDK installation failed: java.nio.file.FileSystemException: C:\Users\prashant\AppData\Local\google\ct4j-cloud-sdk\LATEST: failed to delete one or more files; see suppressed exceptions for details.
> 
> 6:02 PM	Dockerfile detection
> 				You may setup Docker deployment run configuration for the following file(s): 
> 				java-guestbook\backend\Dockerfile
> 				java-guestbook\frontend\Dockerfile
> 				java-hello-world\Dockerfile
> 				Disable this notification (show balloon)
> 
> 6:04 PM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@api.something.net
> 
> 6:45 PM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@api.something.net
> 
> 8/19/2019
> 9:52 AM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@api.something.net
> 
> 10:31 AM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@api.something.net
> 
> 10:35 AM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@api.something.net
> 
> 12:04 PM	Kubernetes Continuous Deploy: Using the current active Kubernetes context: api.something.net/prashant@api.something.net

**Comment by kiran0707** [comment] 2019-10-16 04:42
> Hi, this should work but for me somehow it is not able to find kubectl in path(which is in the path) and not allowing me to save the env variable hence I am not able to apply the changes. Will debug and verify the same.

I am facing same issue too. It worked fine for previous versions.

**Comment by etanshaul** [comment] 2019-10-16 15:53
@kiran0707 are you using custom or managed deps. To check, go to Settings -> Cloud Code -> Kubernetes:
![image](https://user-images.githubusercontent.com/1735744/66936349-88af3100-f00b-11e9-982e-b8a24cf24518.png)

If you select `Use custom specified dependencies` (and don't provide a path), Cloud Code should find the dependencies on your PATH.

**Comment by etanshaul** [comment] 2019-10-21 14:38
@prary, this issue seems to have evolved as a duplicate of https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2642. Going to close this one in favor of that issue for now. Feel free to reopen as needed.

**Closed by etanshaul** 2019-10-21 14:38 UTC
Labels: Kubernetes, P1, feature request
