### ISSUE TITLE
Intellij becomes unresponsive when using Cloud Code  

### ISSUE THREAD

**Issue by JJRdec** [GoogleCloudPlatform/cloud-code-intellij#3087] opened 2022-07-28 13:33 UTC
### Expected Behavior
App shouldn't become unresponsive. 

### Actual Behavior
Using "Cloud Code kubernetes" run configs to run and debug apps in my local cluster (docker desktop). When stopping a debug session the application regularly becomes responsive and most be killed via task manager.

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Intellij
- IDE version:  221.5921.22
- Cloud Code version (Settings > Plugins > Cloud Code): 
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: yes
  - Version of the Cloud SDK: 395.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v1.39.1
- Operating System: Windows 11 (10.0.22000)

### Recreate
1. Debug/run session is active 
2. I try to stop session
3. Its un responsive, the debug session doesn't end
4. I by closing the tab for the session
![image](https://user-images.githubusercontent.com/94698858/181525184-24501ba9-eb9d-42da-b022-2d3de6a74f47.png)
5. Waiting for process to detach starts
![image](https://user-images.githubusercontent.com/94698858/181523049-cc22c3ee-244f-45bd-a70e-6a1b5d50f0b2.png)
6. I try to run a new debug session - the application is unresponsive. (We can see the debug button is frozen on the click)
![image](https://user-images.githubusercontent.com/94698858/181523796-8a9c179e-6554-4289-a2f6-931efbfd6f06.png)

There are loads of Intellij processes (CMD, kubectl.exe, ) running when using Cloud Code, maybe that could be the culprit.

![image](https://user-images.githubusercontent.com/94698858/181521761-1cbb3ca4-e3cc-4ab1-92b2-8487b1d0d6b4.png)

![image](https://user-images.githubusercontent.com/94698858/181524052-c58c5df6-9452-43f1-a401-330049a6ba09.png)

**Comment by etanshaul** [comment] 2022-07-28 14:23
this is extremely helpful. thanks @JJRdec . We will look into this.

**Comment by peterlin741** [comment] 2022-08-03 04:14
@JJRdec, could you provide us with the exact version of the Cloud Code plugin you are using? You can find this at `Preferences > Plugins` (e.g. `22.7.1-221`)

![image](https://user-images.githubusercontent.com/58699538/182522461-7fe510ac-2142-4b2f-9742-8a54e7dc0f33.png)

**Comment by JJRdec** [comment] 2022-08-03 08:38
> @JJRdec, could you provide us with the exact version of the Cloud Code plugin you are using? You can find this at `Preferences > Plugins` (e.g. `22.7.1-221`)

Yes its the latest... 22.7.1-221

![image](https://user-images.githubusercontent.com/94698858/182563794-53a6686b-df0f-4e77-bbde-a3d2803a1663.png)

**Comment by JJRdec** [comment] 2022-08-03 09:00
Also, my Skaffold setup is similar to this example: [Multi-config example](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/multi-config-microservices)

**Comment by etanshaul** [comment] 2022-08-03 15:26
@JJRdec we are actively investigating. We are able to repro occasionally, but not consistently. It seems related to simultaneous browsing of resources in the Kubernetes explorer (all of those kubetcl processes are "watch" processes, to allow us to autoupdate the tree as your Kubernetes resources change) - is this consistent with what you are seeing?

**Comment by JJRdec** [comment] 2022-08-03 15:32
> @JJRdec we are actively investigating. We are able to repro occasionally, but not consistently. It seems related to simultaneous browsing of resources in the Kubernetes explorer (all of those kubetcl processes are "watch" processes, to allow us to autoupdate the tree as your Kubernetes resources change) - is this consistent with what you are seeing?

No, its occasionally - maybe every 3-5 debug sessions. I am also dealing with 3/4 deployments (multi-config Skaffold) which I'm sure isn't helping. Is there a way to disable to Kubernetes Explorer feature for now within Intellij?

**Comment by etanshaul** [comment] 2022-08-03 15:52
>  Is there a way to disable to Kubernetes Explorer feature for now within Intellij?

If, after starting the IDE, you simply never open that panel, it should be equivalent. You can also open the toolbar, click on setting and select `remove from sidebar` (you may want to force kill any kubectl processes after this just to isolate that away). After doing all this, I'd be curious if the issue goes away completely for you.

**Comment by JJRdec** [comment] 2022-08-03 16:08
Unfortunately, after removing the Kubernetes Explorer from the sidebar and restarting Intellij the issue persists. 

I had to start and stop debug session 5 times or so. But the processes kept growing to around 150 and then I couldn't stop the debug once again - Intellij became unresponsive and described before. 
   
![image](https://user-images.githubusercontent.com/94698858/182655637-16d96a54-c915-48b5-9721-7a024346e50b.png)

![image](https://user-images.githubusercontent.com/94698858/182655711-752ddb59-3c8b-4b39-9c25-688dca3e62ad.png)

**Comment by etanshaul** [comment] 2022-08-03 16:13
@JJRdec I think we understand why all those `kubectl` processes are being launched (despite the explorer tree being open). We will fix this bug asap.

We are still investigating to root cause of _why_ those processes are preventing the session from being stopped (and ultimately freezing things up).

**Comment by etanshaul** [comment] 2022-08-03 19:23
We have a partial fix for this. It should take care of most scenarios. We'll update when it is released (hopefully soon, this week).

**Comment by peterlin741** [comment] 2022-08-04 19:53
This has been fixed in `22.8.1`. Thanks for the feedback!

**Comment by etanshaul** [comment] 2022-08-04 20:10
@JJRdec feel free to reach out if you still run into any issues here

**Closed by etanshaul** 2022-08-04 20:10 UTC
