### ISSUE TITLE
Excessive memory consumption on Idea 2019.3.4

### ISSUE THREAD

**Issue by vkruglov** [GoogleCloudPlatform/cloud-code-intellij#2726] opened 2020-03-19 13:54 UTC
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.) 🆗 

- Cloud Code for IntelliJ version: 20.2.1
- OS: MacOS Catalina 10.15.3

**What did you do?**
Updated Idea to the latest version and restarted IDE.

**What did you expect to see?**
Normal startup.

**What did you see instead?**
Skaffold process with Idea as parent has taken up to 65GB of RAM in a matter of seconds. 
Later on skaffold was terminated (not by me).

I disabled custom plugins in IDE and the issue disappeared. By turning on the plugins one by one I found that the issue occurs when Cloud Code plugin is enabled.

<img width="1490" alt="Screenshot 2020-03-19 at 13 04 41" src="https://user-images.githubusercontent.com/7443432/77074637-2f0bc200-6a02-11ea-8a0c-509b91f100da.png">
<img width="2032" alt="Screenshot 2020-03-19 at 13 03 55" src="https://user-images.githubusercontent.com/7443432/77074643-303cef00-6a02-11ea-994c-f0ba8a78d454.png">
<img width="2045" alt="Screenshot 2020-03-19 at 13 03 35" src="https://user-images.githubusercontent.com/7443432/77074646-30d58580-6a02-11ea-97fc-e6eead470ac0.png">

**Comment by etanshaul** [comment] 2020-03-19 13:58
Thanks for reporting @vkruglov 

@fsladkey could you please investigate/repro and loop in Skaffold as needed?

**Comment by fsladkey** [comment] 2020-03-19 14:26
Yep! Taking a look now.

**Comment by fsladkey** [comment] 2020-03-19 15:09
Hey @vkruglov, thanks for this report!

I'm trying to reproduce the behavior you described, running the same version of the plugin and MacOS. I've tried Community/Ultimate and so far memory consumption is reasonable, about 14-15MB  for the skaffold process when it's running.

Could you confirm that you are using the version of skaffold managed by the plugin, and if not which version you're using? You can check in Preferences -> Other Settings -> Cloud Code -> Kubernetes on this panel.
![Screen Shot 2020-03-19 at 11 02 40 AM](https://user-images.githubusercontent.com/12353283/77081528-2c44a900-69d1-11ea-9d5f-087bf73e14c2.png)

If there's any other information you could give us like logs, or nature of the project you're open, etc, that may help as well.

**Comment by fsladkey** [comment] 2020-03-19 15:39
Something you could try is installing [Skaffold v1.5.0](https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.5.0) and configuring Cloud Code to use it on the same settings page I mentioned in the previous comment. This version of Skaffold skips analyzing large files during initialization which could potentially be the cause of your problem.

**Comment by vkruglov** [comment] 2020-03-19 17:21
Hey @fsladkey thanks for your response! 

I've checked the version, it's a managed one (v1.3.1).
The project is Java/Spring/Hibernate/microservices.

> This version of Skaffold skips analyzing large files
There is indeed a correlation here!
I'm currently working with DB dumps and I have several large files in the project. I moved the largest ones outside the project directory and skaffold consumption went down to 1,7GB. 

So I assume the issue is clear and workaround with Skaffold v1.5.0 should work.

**Comment by fsladkey** [comment] 2020-03-19 17:33
That's great! Thanks for your help confirming the issue. Our next release will also update the managed version of Skaffold so you won't have to use that workaround once that's released. :)

**Comment by etanshaul** [comment] 2020-03-19 17:35
thanks @vkruglov, and @fsladkey for troubleshooting.

cc @nkubala @dgageot from Skaffold side to look into improving dealing with large file

**Comment by etanshaul** [comment] 2020-05-11 17:47
closing as Skaffold was since updated with the optimization

**Closed by etanshaul** 2020-05-11 17:47 UTC
Labels: area/skaffold
