### ISSUE TITLE
Empty Dockerfile required to use cloud buildpacks on Cloud Run local

### ISSUE THREAD

**Issue by amammay** [GoogleCloudPlatform/cloud-code-intellij#2872] opened 2021-01-10 14:56 UTC
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

Replication of issue Repo https://github.com/amammay/cloud-code-issue

### Expected Behavior

Not required to have a dockerfile in the repo.

### Actual Behavior

When using the run configuration for cloud run local and having the buildpacks set, when i go to run the configuration i get 

```
Failed to generate the temp pods and services spec

ERROR: (gcloud.alpha.code.export) /Users/username/workspaces/git/cloud-run-master/Dockerfile does not exist.
```

If i create an empty dockerfile it will go ahead and use the buildpacks like expected.

### Additional Information

If i use vsode i get the expected behavior from the get-go

- IDE type (e.g. IntelliJ, Pycharm): Intellij Ultimate
- IDE version: 2020.3.1
- Cloud Code version (Settings > Plugins > Cloud Code):  20.12.2-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK) 
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: 320.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 1.17.2
- Operating System: Mac Big Sur

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment] 2021-01-11 15:33
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3282)

**Comment by etanshaul** [comment] 2021-01-11 15:35
thanks @amammay this sounds like a bug, thanks for reporting. To confirm, by "having buildpacks set", you mean that in the Run Configuration UI builder settings you changed the builder type to buildpacks (indeed you shouldn't need a Dockerfile in this case)?

We'll investigate.

**Comment by amammay** [comment] 2021-01-11 15:36
@etanshaul yup thats it!

**Comment by etanshaul** [comment] 2021-01-11 15:38
while I don't think the issue is language specific, just to be sure - would you mind sharing what language you are using (Java? Python?)? thanks

**Comment by amammay** [comment] 2021-01-11 15:39
@etanshaul golang, i have the repo here https://github.com/amammay/cloud-code-issue with my intellij config checked in and my vscode config checked in.

**Comment by etanshaul** [comment] 2021-01-11 15:40
very helpful. thanks.

**Comment by matthewmichihara** [comment] 2021-01-12 17:23
I'm able to reproduce and I think I've narrowed down the issue - it looks like we aren't properly passing the `--builder` flag to the underlying `gcloud alpha code export` command for buildpack builds.

**Comment by matthewmichihara** [comment] 2021-01-14 18:57
@amammay This should be fixed now in the nightly builds, and will be included in our next release.

I tested with your sample project (which was really helpful, thanks!) and buildpacks builds work again. Feel free to try it out on your own with the latest nightly build at https://plugins.jetbrains.com/plugin/8079-cloud-code/versions/nightly/107710. Make sure you're using a build ending in `2020.2` if installing in IntelliJ 2020.3.

**Closed by matthewmichihara** 2021-01-14 18:57 UTC
Labels: area/cloud-run, kind/bug, priority/p2

**Comment by amammay** [comment] 2021-01-16 14:16
@matthewmichihara thanks much!
