### ISSUE TITLE
Error report submission timed out

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-code-intellij#2663] opened 2019-10-22 17:59 UTC
(Please ensure you are running the latest version of Cloud Cloud for IntelliJ with _Help > Check for Updates_.)

- Cloud Code for IntelliJ version: IntelliJ Ultimate 2019.2.3
- OS: 10.14.6

**What did you do?**

Received an error upon startup after Cloud Code update. Clicked to report error and submitted it.

**What did you expect to see?**

Error submitted.

**What did you see instead?**

"Connect timed out" error popup
![image](https://user-images.githubusercontent.com/1998883/67315131-ed6aff80-f4d3-11e9-8327-acf15252336d.png)

**Comment by etanshaul** [comment] 2019-10-22 20:35
I'll investigate this one. I suspect its just a transient network issue (which would be hard to confirm), but I'll at least validate that things are working correctly.

**Comment by etanshaul** [comment] 2019-10-29 14:16
@saturnism I'm going to close this one for the following reasons:

- I'm not able to reproduce
- The error that you got was at least a nice one (`connection timed out` instead of some exception)
- I can only assume this really was an intermittent network issue.

Let me know if you disagree / feel free to reopen

**Closed by etanshaul** 2019-10-29 14:16 UTC
Labels: P2, needs-investigation, plugin-general
