### ISSUE TITLE
Already disposed project in `ClientStateHolder`

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2718] opened 2020-02-25 15:19 UTC
https://listnrcrash.corp.google.com/product/717949/report/1000000649496802903

```
java.lang.AssertionError: Already disposed: Project (name=Library_management_system_GUI_Python, containerState=DISPOSE_COMPLETED, componentStore=G:\PROJECT\Library_management_system_GUI_Python) 
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$0(ComponentManagerImpl.java:153)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:825)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:71)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:64)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:151)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:144)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:286)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at com.google.cloud.tools.intellij.languageclient.ClientStateHolder$Companion.instance(ClientStateHolder.kt:41)
	at com.google.cloud.tools.intellij.languageclient.YamlEditorWatcher.<init>(YamlEditorWatcher.kt:50)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent$setupServer$2.invokeSuspend(LanguageServerProjectComponent.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by etanshaul** [comment] 2020-03-02 16:39
@peterlin741 to check if this is a dup, and close if so

**Comment by peterlin741** [comment] 2020-03-02 21:28
Will close, This is a duplicate of https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2234

The stack trace is mostly the same, although starts to differ halfway through, Will into this issue from https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2234 for reference

**Closed by peterlin741** 2020-03-02 21:28 UTC
Labels: area/lsp, kind/crash-report, priority/p2
