### ISSUE TITLE
Cloud Source Repo git URL is breaking operations

### ISSUE THREAD

**Issue by Mike-Kharkov** [GoogleCloudPlatform/cloud-code-intellij#2595] opened 2019-06-18 00:00 UTC
Hi!
I have some problems(with my customer) with connecting to his GIT storage.
We have the next parameters:
https://source.cloud.google.com/kurjer-211511?hl=de
https://clip2net.com/s/426pfEW

After attempts connecting to storage we have this error:
https://clip2net.com/s/426pf6r

Why is it happening?

**Comment by etanshaul** [comment] 2019-06-18 13:51
hi @Mike-Kharkov thanks for the report!

We are able to reproduce this and will investigate and put out a fix.

**Comment by etanshaul** [comment] 2019-06-18 16:00
Update:

We identified the source of the issue. If you notice in the "Clone" UI, the name of the repository is fully qualified as follows:

`projects/[gcp project]/repos/[rep name]`.

This is a change in the API from the previously expected value of just `[repo name]`. Ultimately this causes the constructed git url to be invalid.

We will fix this in the next release. But in the meantime, you can clone the repository via the command line using:

`git clone https://source.developers.google.com/p/[gcp project]/r/[repo name]`, making sure to replace the gcp project and the repository name.

**Comment by Mike-Kharkov** [comment] 2019-06-19 23:09
Hi!
We tried to use this command - but it is not worked - Why?

**Comment by Mike-Kharkov** [comment] 2019-06-20 13:39
sageprice - why did you close my post?

**Comment by sageprice** [comment] 2019-06-20 13:40
Sorry Mike - did not intend to close. Made a commit which should fix the original issue and it auto-closed this. I'm not sure what the cause of the new error is, trying to look into it.

**Comment by sageprice** [comment] 2019-06-20 14:10
Sorry to say I'm having trouble finding anything related specifically to `Forbidden-upload-pack` errors. Assuming that credentials have been properly set up following the [cloud source repositories documentation](https://cloud.google.com/source-repositories/docs/cloning-repositories#using_manually_generated_credentials), I'm not sure what else to try here.

Have you tried to clone using the [Google Cloud SDK](https://cloud.google.com/source-repositories/docs/cloning-repositories#using_cloud_sdk) or the CSR console? If so, what errors do you see from there?

If none of these approaches are working, I'd highly recommend [filing a bug against Cloud Source Repositories for support](https://cloud.google.com/source-repositories/docs/getting-support). I'm afraid that the Cloud Code team does not have a lot of insight into what is happening with CSR.

**Comment by etanshaul** [comment] 2019-06-20 15:40
Agreed with what @sageprice said - I also encourage you to try and follow the CSR official documentation to see if you can get it working, since that failure it outside of the control of the Cloud Code plugin.

In the meantime - we have fixed the issue in Cloud Code and the fix will be available in our next release.

**Comment by Mike-Kharkov** [comment] 2019-06-21 08:15
And when it new fixed release should appear?

**Comment by etanshaul** [comment] 2019-06-21 14:53
Hi @Mike-Kharkov the release should happen within the next 2-3 weeks. We are still finalizing a couple items.

In the meantime, if you wanted to try to see if the unreleased fix in the plugin works for you, you can install our nightly release. Keep in mind that this is bleeding edge unreleased features and therefore may not be as stable. To install the nightly release, follow the steps here under "pre-releases":
https://github.com/GoogleCloudPlatform/cloud-code-intellij#pre-releases

And ensure to replace `alpha` with `nightly`.

**Comment by etanshaul** [comment] 2019-08-09 20:14
@Mike-Kharkov this was released as part of our last release 19.7.2

Closing for now. Feel free to reopen if you run into anything.

**Closed by etanshaul** 2019-08-09 20:14 UTC
Labels: bug, cloud repos
