### ISSUE TITLE
Can't create idex mode=geospatial

### ISSUE THREAD

**Issue by buttonsquared** [GoogleCloudPlatform/cloud-code-intellij#2602] opened 2019-07-07 21:17 UTC
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_)
- Cloud Tools for IntelliJ version: 18.12.1
- Google Cloud SDK version: 253.0.0
- OS: Mac OS X 10.13.6

**What did you do?**
Deploy my app gives error can't create index permission denied
**What did you expect to see?**
index created
**What did you see instead?**
permission denied 
(screenshots are helpful)
_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by sageprice** [comment] 2019-07-09 15:03
Hey @buttonsquared, sorry to hear you're running into this error. I think we need some additional information to help investigate this, hard to say what is going on with just permission denied.

1. What action led to this error? Is it `Deploy to AppEngine`? 
1. What are you trying to create indices for?
1. What is the exact error displayed?

Please also run a quick `gcloud auth login` to verify that you are logged in and gcloud is working.

**Comment by sageprice** [comment] 2019-07-09 15:15
Wondering if this could be related to https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2601

**Comment by etanshaul** [comment] 2019-08-23 15:51
@buttonsquared closing for now since we can't reproduce. But please feel free to follow up with more details if you are still running into this. Thanks!

**Closed by etanshaul** 2019-08-23 15:51 UTC
Labels: P2, bug, user reported
