### ISSUE TITLE
IntelliJ IDEA 2023.1.3 Blocks the keyboard in different model windows

### ISSUE THREAD

**Issue by IliyaBrook** [GoogleCloudPlatform/cloud-code-intellij#3144] opened 2023-06-25 08:49 UTC
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior
For example I'm press on shift+f6 on folder or file the, rename modal windows appears, escape not working,
can't typing, only can use mouse to close window or other action

### Actual Behavior
press on shift+f6 on folder or file, the typing need to work

### Additional Information
when i'm turn of the plugin, this functionality works as expect,
turn the plugin again, the and this bug is back again
plugin version 

- IDE type (e.g. IntelliJ, Pycharm):
- IDE version:  IntelliJ IDEA 2023.1.3 (Ultimate Edition)
- Cloud Code version (Settings > Plugins > Cloud Code): 23.6.1-api-version-222
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK:  yes
  - Version of the Cloud SDK: 436.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: Windows 11 Pro 64-bit , Windows Feature Experience Pack 1000.22642.1000.0

![idea64_TSv5I3zwEz](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/60712617/9d0e7d86-8201-4f6c-855a-a20b6198d092)

**Comment by andrey-bondar** [comment] 2023-06-26 11:26
I have same issue

**Comment by itzg** [comment] 2023-06-26 12:37
This has impacted quite a few users https://youtrack.jetbrains.com/issue/IDEA-323532

**Comment by etanshaul** [comment] 2023-06-26 14:13
thanks for reporting. we are looking into this

**Comment by etanshaul** [comment] 2023-06-26 15:56
we have a fix. we are doing some final testing and will release a new version of the plugin today asap.

**Comment by etanshaul** [comment] 2023-06-26 17:43
We released a fix. Please update to Cloud Code version 23.6.2 which contains the fix. Sorry for the inconvenience

**Comment by CrazyCoder** [comment] 2023-09-18 17:09
Similar issue was reported for Google Cloud Code (23.9.1-api-version-222):

https://youtrack.jetbrains.com/issue/IDEA-332712

**Comment by etanshaul** [comment] 2023-09-18 17:12
Thanks. We'll check if there was a regression here in the latest version.

**Comment by andrey-bondar** [comment] 2023-09-19 09:47
![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/3185843/46881785-f3f6-4977-9407-07a6217c9ec6)

Typing class name is blocked in "Create new PHP class" modal after the plugin upgrade. Disabling the plugin resolves this issue.

**Comment by etanshaul** [comment] 2023-09-19 13:57
@CrazyCoder @andrey-bondar to confirm, are you using `23.9.1-api-version-222` (or higher)? I was not able to reproduce this problem.

Could you possibly provide a few more details to help us get to the bottom of this:
- Version of Cloud Code
- Version and flavor of the IDE
- Some brief repro steps (e.g. in which GUI element you experienced this issue, and how to repro).

Thanks!

**Comment by etanshaul** [comment] 2023-09-19 14:09
Noting that this is not reproducible in 23.8.2. So it does in fact look like a regression in the September release. This should make it easier to pinpoint. Will update again when we find the issue.

**Comment by etanshaul** [comment] 2023-09-19 15:16
Update: we located the regression. We are evaluation fixes as well as safeguards to prevent this sort of thing. Stay tuned for updates on a release with the fix.

**Comment by etanshaul** [comment] 2023-09-20 13:47
`23.9.3` has been released with a fix for this. Closing for now. Feel free to follow up here as needed. Thanks.

**Closed by etanshaul** 2023-09-20 13:47 UTC
