### ISSUE TITLE
TimeoutException: Time out reading managed Cloud Run services when Cloud Run API is not enabled

### ISSUE THREAD

**Issue by mriswithe** [GoogleCloudPlatform/cloud-code-intellij#2851] opened 2020-11-17 23:03 UTC
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior
Cloud Run tab loads services from google
### Actual Behavior
Time out error:
![image](https://user-images.githubusercontent.com/1725647/99460909-5d75d000-28f6-11eb-9f8d-9607c9b2265b.png)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): PyCharm
- IDE version: 2020.2.3 PRO
- Cloud Code version (Settings > Plugins > Cloud Code): 20.10.1-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK:  yes
  - Version of the Cloud SDK: 319.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: Windows 10

Hadn't used cloud code plugin for awhile and I am working on an appengine app, and it seemed like the plugin might have some integrations, but I can't get it to show me anything. Tried uninstalling and reinstalling the plugin, reauthing both via `gcloud auth application-default login` and via the cloud run tab. Not sure what else to do, no strange firewall/proxy on my end. Just a home internet connection.

**Comment by ivanporty** [comment] 2020-11-18 00:16
Thanks for the report @mriswithe! It looks like Cloud Run Services view does not load services unless Cloud Run API is enabled for the selected project. We will fix this so it will ask you if you want to enable the API when it's not enabled.

Meanwhile, to enable Cloud Run API, there are couple of ways:
* Deploy to Cloud Run using this Cloud Code run configuration (add new run configuration and deploy)

<img width="378" alt="Screen Shot 2020-11-17 at 7 11 39 PM" src="https://user-images.githubusercontent.com/11686100/99465606-c8300700-2908-11eb-9c05-0d5ce383dced.png">

Deploying an application will automatically enable Cloud Run API, and you should be able to see the service in the list then.

* If you're not ready to deploy, use Cloud Console to enable the API:

https://console.developers.google.com/apis/api/run.googleapis.com
<img width="466" alt="Screen Shot 2020-11-17 at 7 15 38 PM" src="https://user-images.githubusercontent.com/11686100/99465915-50161100-2909-11eb-9d01-4e78ee92df8d.png">

Once enabled, try refreshing the service view and it should load (although it's supposedly will be empty before you deploy any services).

**Comment by ivanporty** [comment] 2020-11-18 00:22
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3044)

**Comment by mriswithe** [comment] 2020-11-18 00:23
Refresh button wouldn't work, but after enabling the API and closing and reopening PyCharm it did indeed bring me back the empty services list. 

Worth noting that after the initial failure, it didn't seem to be interested in trying again, even if I switched which project it should look at. 

But the workaround worked! Want me to close this or leave it open until the fix is in place for people to discover it?

**Comment by ivanporty** [comment] 2020-11-18 00:26
It should definitely just try again, I suspect the API enablement just took some time, we'll figure this out as well.
Thanks for quick confirmation!
Let's keep this open for other people too, if you don't mind, I will tweak title a bit to ensure it reflects the root cause.

**Comment by mriswithe** [comment] 2020-11-18 00:29
Sounds good to me! thanks for the help. I assume you can close it once you all are satisfied?

**Comment by ivanporty** [comment] 2020-11-18 00:30
Yes, we should detect this scenario and offer you an option to enable Cloud Run API without having to go to Cloud Console. Once we update the service view, we will close it, thanks!

**Comment by etanshaul** [comment] 2021-01-22 16:02
@ivanporty could you help triage this (move to internal repo etc.)? Wanna make sure we resolved this.

**Comment by ivanporty** [comment] 2021-01-22 17:58
Yes, makes sense, this should be a good fix to have.

**Comment by matthewmichihara** [comment] 2021-03-18 15:41
This should be fixed in the next release. The Cloud Run tool window will now show a link to enable the Cloud Run API if not already enabled.

**Closed by matthewmichihara** 2021-03-18 15:41 UTC
Labels: area/cloud-run, kind/bug, priority/p2
