### ISSUE TITLE
Cloud Code plugin breaks AWS CloudFormation YAML tag validation

### ISSUE THREAD

**Issue by mil1i** [GoogleCloudPlatform/cloud-code-intellij#2689] opened 2020-01-11 23:47 UTC
- Cloud Code for IntelliJ version: 19.12.1
- OS: macOS Catalina 10.15.2

**What did you do?**
With the [AWS Cloudformation](https://plugins.jetbrains.com/plugin/7371-aws-cloudformation/) plugin also installed at the same time as this Cloud Code plugin, it breaks YAML tag validation (eg, !Sub, !Ref, !Join) used in Cloud Formation templates.

After disabling the Cloud Code plugin, the tags are no longer marked as "unknown tag". This issue also occurs in VS Code if you have the Cloud Code extension installed and do not add those custom tags manually to the settings even if they are set in the Red Hat YAML extension settings. I do not see any way to add custom tags for this plugin in IntelliJ.

**What did you expect to see?**
No errors on AWS CloudFormation YAML tags.

**What did you see instead?**
unknown tag <!Sub>, unknown tag <!Ref>, etc.

(screenshots are helpful)

**Comment by matthewmichihara** [comment] 2020-01-13 15:13
Thanks for the report @mil1i . Can you point me to a sample YAML file with custom tags that I can try to reproduce this issue with?

**Comment by etanshaul** [comment] 2020-01-13 15:18
@kschaab fyi regarding the following. It sounds like we might need some investigation in VS Code as well:

> This issue also occurs in VS Code if you have the Cloud Code extension installed and do not add those custom tags manually to the settings even if they are set in the Red Hat YAML extension settings.

**Comment by mil1i** [comment] 2020-01-13 17:03
I cannot share my Cloud Formation files, but here is a link to a publicly posted one that I still see the issue with in my IntelliJ (fyi; it does not through the errors in a scratch file, but it does when it is a file in the project).

https://raw.githubusercontent.com/awslabs/aws-cloudformation-templates/master/aws/services/CloudFormation/FindInMap_Inside_Sub.yaml

As for the VS Code, there is a workaround and it is currently working fine but (I believe) it would be best if it took in the custom tags from the YAML extension so that you did not need to duplicate your settings.

Eg:
```
    // Custom tags for the parser to use
    "yaml.customTags": [
        "!And",
        "!If",
        "!Not",
        "!Equals",
        "!Or",
        "!FindInMap sequence",
        "!Base64",
        "!Cidr",
        "!Ref",
        "!Sub",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Select",
        "!Select sequence",
        "!Split",
        "!Join sequence"
    ],
    // Enable/disable default YAML formatter (requires restart)
    "yaml.format.enable": true,
    // Custom tags for the parser to use
    "cloudcode.yaml.customTags": [
        "!And",
        "!If",
        "!Not",
        "!Equals",
        "!Or",
        "!FindInMap sequence",
        "!Base64",
        "!Cidr",
        "!Ref",
        "!Sub",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Select",
        "!Select sequence",
        "!Split",
        "!Join sequence"
    ],
```

**Comment by mil1i** [comment] 2020-01-13 17:04
![image](https://user-images.githubusercontent.com/8459426/72275860-b285ed00-3626-11ea-936b-e352c8bb67c9.png)

**Comment by etanshaul** [comment] 2020-04-15 18:16
@peterlin741 could you remind me - did you file an issue on the AWS Cloud Formation plugin to improve the way they handle yaml files (or was this something else)?

**Comment by peterlin741** [comment] 2020-04-15 18:40
> @peterlin741 could you remind me - did you file an issue on the AWS Cloud Formation plugin to improve the way they handle yaml files (or was this something else)?

It was a request for the  Kubernetes OpenShift plugin (https://github.com/tinselspoon/intellij-kubernetes/issues/15)

**Comment by edthorne** [comment] 2020-05-18 18:05
I opened an issue back in January with [JetBrains](https://youtrack.jetbrains.com/issue/IDEA-230900) for the CloudFormation plugin. However, like the original poster, when I disable the Cloud Code plugin the problem goes away. Both plugins are clearly interested in YAML files for the purposes of validation. Not being a plugin developer I'm not certain what remedy is available.

**Comment by matthewmichihara** [comment] 2020-05-18 20:29
This is an issue on Cloud Code's side, and unfortunately I don't see any great workarounds until this is fixed.

**Comment by etanshaul** [comment] 2020-05-21 23:49
@matthewmichihara what can we do on the Cloud Code side to improve this?

**Comment by matthewmichihara** [comment] 2020-05-26 13:01
I think we need to make our language server ignore custom tags instead of return errors (https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/1138#issuecomment-573899131).

**Comment by etanshaul** [comment] 2020-05-26 13:40
@mil1i and @edthorne . We are currently triaging this issue and discussing the best approach here:

1) Add the ability to disable Cloud Code from attempting to validate _an entire file_. For Cloud Formation files, for example, you'd then be able to exclude that file from being validated by Cloud Code

or

2) Add the ability to take in custom tags in Cloud Code so that the tags (in this case coming from CloudFormation) are recognized by Cloud Code and not presented as errors.

We are thinking 1 is a more generally useful feature (and leaning towards it), but 2 is more flexible. We'd love to hear your thoughts.

**Comment by edthorne** [comment] 2020-05-26 14:57
I think either option would work in this case. I'd put my vote on simply skipping the entire file. I know from earlier comments that option 2 is already present in other solutions and might be beneficial to others migrating from those solutions.

Because I'm primarily using the plugin for the Kubernetes Explorer I think I'm overlooking something. I want to follow up with a question of my own. What value add is the plugin adding to YAML validation that isn't already included in the JetBrains Kubernetes plugin or normal YAML validation? I bring this up as a point of discussion and an observation that JetBrains can tell the difference between ordinary YAML files and k8s related files based on the content. An ordinary YAML file is recognized as k8s config by the presence of the `apiVersion` and `kind` tags.

I don't know what functionality is available to the plugin to decide on validation strategies. However, with the above in mind, I took a look at the [Template Anatomy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html#template-anatomy-sections) help topic for CloudFormation to see if we could leverage the YAML content to decide not to perform validation. The `AWSTemplateFormatVersion` section/element isn't strictly required in the YAML, only the top level `Resources` is. I was hesitant to bring this up because putting logic in this plugin to exclude files based on other content leads down a rabbit hole. However, it might be an alternative to the two options above to allow configuration of tags that would skip validation entirely on the file. An "if you see this tag, skip validation" type of a solution.

**Comment by mil1i** [comment] 2020-05-26 17:43
I pretty much agree with the above. I was also primarily using this extension when I was working on a project running on Kubernetes. Currently I have been working on another project that does not and have since disabled this plugin due to it's interference with Cloudformation templates.

The way I see it, if this plugin does not make use of Custom YAML tags nor have any intention to, ignoring them as @matthewmichihara mentioned above makes the most sense to me.

**Comment by etanshaul** [comment] 2020-05-26 21:42
thanks for your feedback. we'll keep all this in mind.

> What value add is the plugin adding to YAML validation that isn't already included in the JetBrains Kubernetes plugin or normal YAML validation?

There is indeed some overlap here. In fact, Cloud Code disables its yaml validation on Kubernetes files that would already be validated by the JetBrains plugin to avoid conflict. In the absence of the JetBrains plugin (if its removed, or in community edition) Cloud Code provides this support.

Additionally Cloud Code provides editing support for several more file types (and the list is always growing). For a full list you can see:
https://cloud.google.com/code/docs/intellij/yaml-editing

**Comment by matthewmichihara** [comment] 2020-08-20 21:44
Update: we are looking at providing UI to specify which YAML files to validate, similar to what Cloud Code for VS Code currently provides in settings:

![image](https://user-images.githubusercontent.com/79073/90828902-cd32e980-e30c-11ea-8957-423ae8babc80.png)

**Comment by etanshaul** [comment] 2020-12-09 20:12
@matthewmichihara looks like we'll need to prioritize adding a fix for this (as you mentioned in your above comment).

**Comment by matthewmichihara** [comment] 2020-12-11 15:52
January's release includes a new setting to specify a YAML file matcher glob pattern (the same as what Cloud Code for VSCode offers) to address this.

**Comment by etanshaul** [comment] 2021-02-03 14:50
Hi all - the last release version `21.2.1` includes this new setting. Please let us know if you still run into any issues. Closing for now.

**Closed by etanshaul** 2021-02-03 14:50 UTC
Labels: area/editing-support, area/lsp, fixed-in-next-release, kind/bug, priority/p2
