### ISSUE TITLE
NoClassDefFoundError SVGDOMImplementation in KubernetesExplorerWindowFactory

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2764] opened 2020-05-12 18:06 UTC
IDEA 2019.3.1
Plugin 20.4.3

```
failed to init toolwindow com.google.cloud.tools.intellij.kubernetes.explorer.KubernetesExplorerWindowFactory
Stack trace:
java.lang.NoClassDefFoundError: org/apache/batik/anim/dom/SVGDOMImplementation$FeOffsetElementFactory
	at org.apache.batik.anim.dom.SVGDOMImplementation.<clinit>(SVGDOMImplementation.java:340)
	at com.intellij.ui.svg.SaxSvgDocumentFactory.<init>(SaxSvgDocumentFactory.kt:28)
	at com.intellij.util.SVGLoader.createTranscodeInput(SVGLoader.java:224)
	at com.intellij.util.SVGLoader.loadWithoutCache(SVGLoader.java:123)
	at com.intellij.util.SVGLoader.load(SVGLoader.java:113)
	at com.intellij.ui.icons.ImageDescriptor.loadImpl(ImageDescriptor.java:143)
	at com.intellij.ui.icons.ImageDescriptor.loadFromStream(ImageDescriptor.java:125)
	at com.intellij.ui.icons.ImageDescriptor.load(ImageDescriptor.java:114)
	at com.intellij.util.ImageLoader$ImageDescriptorList.load(ImageLoader.java:152)
	at com.intellij.util.ImageLoader.loadFromUrl(ImageLoader.java:308)
	at com.intellij.util.ImageLoader.loadFromUrl(ImageLoader.java:297)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadFromUrlImpl(IconLoader.java:763)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadFromUrl(IconLoader.java:737)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.access$900(IconLoader.java:562)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon$MyScaledIconsCache.getOrScaleIcon(IconLoader.java:796)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:640)
	at com.intellij.ui.icons.LazyImageIcon.getRealIcon(LazyImageIcon.java:76)
	at com.intellij.ui.icons.LazyImageIcon.getIconHeight(LazyImageIcon.java:65)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setIcon(ToolWindowImpl.java:404)
	at com.google.cloud.tools.intellij.kubernetes.explorer.KubernetesExplorerWindowFactory.init(KubernetesExplorerWindowFactory.kt:88)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setContentFactory(ToolWindowImpl.java:525)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindow(ToolWindowManagerImpl.java:477)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$6.run(ToolWindowManagerImpl.java:453)
	at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
	at com.intellij.openapi.wm.impl.CommandProcessor.flush(CommandProcessor.java:32)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.flushCommands(ToolWindowManagerImpl.java:585)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$3100(ToolWindowManagerImpl.java:74)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$InitToolWindowsActivity.lambda$runActivity$0(ToolWindowManagerImpl.java:2289)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
```

**Comment by etanshaul** [comment] 2020-05-12 18:12
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/1862)

**Comment by peterlin741** [comment] 2020-11-04 19:29
Unable to reproduce, closing until we see more instances

**Closed by peterlin741** 2020-11-04 19:29 UTC
Labels: area/k8s-explorer, priority/p3
