### ISSUE TITLE
User reported: AnsiEscapeDecoder AssertionError in AppEngineStandard

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2621] opened 2019-08-01 14:25 UTC
```
java.lang.AssertionError at AnsiEscapeDecoder.escapeText : __NONE___
Stack trace:
java.lang.AssertionError
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:58)
	at com.intellij.remoteServer.impl.runtime.log.LoggingHandlerImpl$Colored.print(LoggingHandlerImpl.java:94)
	at com.google.cloud.tools.intellij.appengine.java.cloud.standard.AppEngineStandardStage.lambda$stage$0(AppEngineStandardStage.java:60)
	at com.google.cloud.tools.appengine.operations.cloudsdk.process.LegacyProcessHandler$1.run(LegacyProcessHandler.java:100)
```

**Comment by etanshaul** [comment] 2019-08-01 14:26
Plugin: 19.7.2
IDE: IJ 2019.2

**Comment by sageprice** [comment] 2019-09-06 15:34
Minor update -- we've gotten a few more reports about this since it was first opened:

- August 19 on 19.7.2 
- August 27 on 19.7.2
- September 6 on 19.9.1

All of these were reported from different regions.

Without investigating too deeply, this seems like a somewhat internal error -- `AnsiEscapeDecoder` tries to read tokens from a buffer using an `AnsiStreamingLexer` via the `getElementText` method, and we fail when the parsed text is `null`. It looks like the lexer is never supposed to have `null` when a token can be parsed to some type, and the code explicitly checks for `type != null` before the assertion, so this seems like an issue with the parsing logic.

Maybe there is something about the AppEngine staging code I'm unfamiliar with that's causing us to see this regularly, but this might be a good case to ask JetBrains for some help.

**Comment by etanshaul** [comment] 2019-09-06 15:43
this someone corresponds with our release of the update to appengine-plugins-core in the end of July. I wonder if anything changed in there that could give us any hints. 

Shot in the dark but @loosebazooka in case anything jumps out.

**Comment by etanshaul** [comment] 2019-11-08 18:10
Anyone have bandwidth to check this one out? If so feel free to reassign to yourself

**Comment by loosebazooka** [comment] 2019-11-11 19:35
I don't have a very good idea of what's going on here. All we do is pass lines of output to the listener, and this code is basically the original code from so long ago repackaged into the LegacyProcessHandler.

**Comment by sllewely** [comment] 2019-11-12 22:00
Not enough info to reproduce / investigate at the moment

**Comment by etanshaul** [comment] 2019-11-12 22:01
ack. thanks @sllewely . I'll take a quick look too when I have a sec, but I doubt I'll see anything you all didn't.

**Comment by fsladkey** [comment] 2020-11-30 15:51
Got another report from IDEA 2020.2.3 with latest plugin version.

**Comment by etanshaul** [comment] 2020-12-09 20:23
reducing the priority on this. As we cannot reproduce and likely affecting a small subset of users.

**Comment by loosebazooka** [comment] 2020-12-09 20:38
Does the report allow us to ask the user if it's consistently happening? or is it anonymous?

**Comment by etanshaul** [comment] 2020-12-09 20:49
anonymous

**Comment by grmoon** [comment] 2021-01-25 04:30
saw this again at: https://listnrcrash.corp.google.com/report/1000000978346061961

**Comment by axmerc** [comment] 2021-04-19 16:19
closing until recurrence

**Closed by axmerc** 2021-04-19 16:19 UTC
Labels: area/app-engine, kind/bug, kind/user-reported, priority/p3, triage/help-wanted
