### ISSUE TITLE
NoSuchFileException for missing language-client jar

### ISSUE THREAD

**Issue by fsladkey** [GoogleCloudPlatform/cloud-code-intellij#2862] opened 2020-12-04 16:38 UTC
## NoSuchFileException for missing language-client jar

IDE Type: IntelliJ IDEA
IDE Version: 2020.3
Plugin Version: 20.10.1-202
OS: Linux

Potentially related to similar but distinct exception reported here https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2825

```
java.nio.file.NoSuchFileException: /<PATH>/JetBrains/Toolbox/apps/IDEA-U/ch-1/203.5981.155.plugins/google-cloud-code/lib/language-client-20.10.1-202.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1838)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
	at com.intellij.util.lang.JarLoader.createZipFile(JarLoader.java:322)
	at com.intellij.util.lang.JarLoader.getZipFile(JarLoader.java:312)
	at com.intellij.util.lang.JarLoader.getResource(JarLoader.java:217)
	at com.intellij.util.lang.ClassPath$ResourceStringLoaderIterator.findInLoader(ClassPath.java:374)
	at com.intellij.util.lang.ClassPath$ResourceStringLoaderIterator.process(ClassPath.java:369)
	at com.intellij.util.lang.ClassPath$ResourceStringLoaderIterator.process(ClassPath.java:366)
	at com.intellij.util.lang.ClasspathCache.iterateLoaders(ClasspathCache.java:150)
	at com.intellij.util.lang.ClassPath.getResource(ClassPath.java:102)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:344)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:315)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:238)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:127)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.google.cloud.tools.intellij.languageclient.YamlEditorWatcher.startWatching(YamlEditorWatcher.kt:79)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent$setupServer$2.invokeSuspend(LanguageServerProjectComponent.kt:121)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent$setupServer$2.invoke(LanguageServerProjectComponent.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:156)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent.setupServer(LanguageServerProjectComponent.kt:61)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent$projectOpened$1.invokeSuspend(LanguageServerProjectComponent.kt:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by fsladkey** [comment] 2020-12-04 16:38
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3148)

**Comment by matthewmichihara** [comment] 2021-02-01 15:20
I do think this has the same root cause as the issue (https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2825) that @fsladkey mentioned. Something strange is happening with the classloader once in a while. Going to close this to consolidate efforts in that issue.

**Closed by matthewmichihara** 2021-02-01 15:20 UTC
Labels: kind/crash-report, priority/p2, triage/needs-investigation
