### ISSUE TITLE
CLion issue finding schema files

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2559] opened 2019-05-14 19:08 UTC
```
java.lang.Throwable: Cannot find file by /schemas/v1beta9.json
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.jetbrains.jsonSchema.extension.JsonSchemaProviderFactory.getResourceFile(JsonSchemaProviderFactory.java:37)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.editing.SkaffoldSchemaFileProvider.getSchemaFile(SkaffoldSchemaFileProvider.kt:46)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getSchemaForProvider(JsonSchemaServiceImpl.java:551)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.access$700(JsonSchemaServiceImpl.java:37)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState.createFileProviderMap(JsonSchemaServiceImpl.java:525)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState.access$500(JsonSchemaServiceImpl.java:455)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.compute(JsonSchemaServiceImpl.java:468)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.compute(JsonSchemaServiceImpl.java:464)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:48)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.getValue(JsonSchemaServiceImpl.java:476)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.getValue(JsonSchemaServiceImpl.java:464)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState.getFiles(JsonSchemaServiceImpl.java:498)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.isMappedSchema(JsonSchemaServiceImpl.java:344)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.isMappedSchema(JsonSchemaServiceImpl.java:340)
	at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.isSchemaFile(JsonSchemaServiceImpl.java:328)
	at com.jetbrains.jsonSchema.ide.JsonSchemaService.isSchemaFile(JsonSchemaService.java:30)
	at com.jetbrains.jsonSchema.impl.JsonSchemaRegexInjector.getLanguagesToInject(JsonSchemaRegexInjector.java:17)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:421)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:343)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:168)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:138)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerate(InjectedLanguageManagerImpl.java:307)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.getInjectedPsiFiles(InjectedLanguageManagerImpl.java:436)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processInjectedFile(LowLevelSearchUtil.java:61)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:133)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:225)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.execute(PsiSearchHelperImpl.java:779)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:232)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:223)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:970)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$6(PsiSearchHelperImpl.java:426)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:43)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:410)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$2(PsiSearchHelperImpl.java:306)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$null$3(PsiSearchHelperImpl.java:363)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$4(PsiSearchHelperImpl.java:362)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:99)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

app.name.version
 CLion
app.version.major
 2019
app.version.minor
 1.3
java.version
 1.8.0_202-release
java.vm.vendor
 JetBrains s.r.o
os.name
 Mac OS X
plugin.version
 19.5.2

**Comment by etanshaul** [comment] 2019-05-14 19:22
@GoogleCloudPlatform/cloud-tools-for-intellij anyone wanna take a look at this?

**Comment by tete17** [comment] 2019-05-22 12:56
Do we have any updates on this issue. 
`kustomization.yaml` files don't work either

**Comment by etanshaul** [comment] 2019-05-22 16:21
Hi @tete17 thanks for reaching out - we are still working on enhanced editing support for other types of tooling (like Kustomize). I don't have any specific timeline to report yet, but it is on our radar.

Just so we understand your needs to make sure we provide the right features: are you looking for basic editing support for Kustomize configs? Things like auto-complete, quick docs, etc.?

Also just to make sure - this specific issue was originally around a possible bug loading the schema for `skaffold.yaml` files - you weren't running into this issue were you?

Thanks!

**Comment by tete17** [comment] 2019-05-22 16:28
Hi @etanshaul 
Thanks for the quick response. i know you guys are busy, wan't my intention to pressure just to get a status update.

For me basic support like schema checking is more than enough

I append an image of what I am seeing, plus the sytnax checking is not working
![Captura de pantalla de 2019-05-22 18-25-16](https://user-images.githubusercontent.com/13263011/58191546-12f2a380-7cbf-11e9-99fe-9b6c4c3b8165.png)
![image](https://user-images.githubusercontent.com/13263011/58191595-2ef64500-7cbf-11e9-866c-d9b27bd47c11.png)

I din't got any error from Clion but I am sure what I am seeing is not correct. If you guide me through the process I am more than willing to provide logs and more details :smile:

**Comment by etanshaul** [comment] 2019-05-22 16:34
oh this is very helpful. So to confirm some facts:

- you are using CLion: which version?
- You are not getting the schema loaded properly for `skaffold.yaml` - this is a bug. We have the schemas (including for version `skaffold/v1beta10`) bundled with the Cloud Code plugin, so it should be working. Also it looks like the list of schemas could use some work - at a minimum each entry in that list should have the version associated with it for easier parsing.

We will investigate this. thanks again!

**Comment by tete17** [comment] 2019-05-22 16:36
```
CLion 2019.1.3
Build #CL-191.7141.37, built on May 6, 2019
Licensed to Miguel Sacristan Izcue
Subscription is active until May 31, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-48-generic
```

Looking forward to the changes. Keep up the good work

**Comment by etanshaul** [comment] 2019-05-22 16:41
Oh I think I know what the problem may be:

Do you have JetBrains Kubernetes plugin also installed? 

If so, we have a known conflict with it: https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2396

The issue is that the JetBrains Kubernetes plugin attempts to do its own validation on the Skaffold file, which looks like a regular k8s manifest. But it doesn't know how to validate it.

We have a plan to correct this, but the fix is only viable in platform versions 2019 and up (currently we support 2018.2 and up), so we have to wait a bit to ensure that most users have upgraded.

In the meantime, we definitely don't want you to uninstall the other plugin, and there is a manual workaround to exclude validation from the Kubernetes plugin on `skaffold.yaml` files. I will add this to our FAQ and update here when ready. (assuming all of this was the source of the problem :) )

**Comment by etanshaul** [comment] 2019-08-23 15:58
closing as we have fixed the original issue in this ticket (around throwing errors for missing schema files). Migrating Kustomize editing request to a new issue.

**Closed by etanshaul** 2019-08-23 15:58 UTC
Labels: Kubernetes, editing, user reported
