### ISSUE TITLE
User reported: Exception calling com.intellij.psi.search.FileTypeIndex.getFiles

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2557] opened 2019-05-13 15:46 UTC
Looks like an internal IDE error, but might need to investigate a bit more.

```
java.lang.RuntimeException: java.io.EOFException
	at com.intellij.util.ExceptionUtilRt.rethrow(ExceptionUtilRt.java:31)
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:120)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.handleError(FSRecords.java:516)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.access$000(FSRecords.java:153)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readAndHandleErrors(FSRecords.java:941)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getNameId(FSRecords.java:1135)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getId(PersistentFSImpl.java:377)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:150)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:80)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:451)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:42)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:54)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath(LocalFileSystemBase.java:46)
	at com.intellij.openapi.vfs.newvfs.ArchiveFileSystem.findLocalByRootPath(ArchiveFileSystem.java:230)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findRoot(PersistentFSImpl.java:1007)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findRoot(PersistentFSImpl.java:57)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.prepare(VfsImplUtil.java:139)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:38)
	at com.intellij.openapi.vfs.impl.jar.JarFileSystemImpl.findFileByPath(JarFileSystemImpl.java:113)
	at com.intellij.openapi.vfs.impl.VirtualFileManagerImpl.findFileByUrl(VirtualFileManagerImpl.java:127)
	at com.intellij.openapi.vfs.VfsUtilCore.findRelativeFile(VfsUtilCore.java:587)
	at com.intellij.javaee.ExternalResourcesRootsProvider$1.compute(ExternalResourcesRootsProvider.java:50)
	at com.intellij.javaee.ExternalResourcesRootsProvider$1.compute(ExternalResourcesRootsProvider.java:35)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at com.intellij.javaee.ExternalResourcesRootsProvider.getAdditionalRootsToIndex(ExternalResourcesRootsProvider.java:62)
	at com.intellij.util.indexing.IndexableSetContributor.getRootsToIndex(IndexableSetContributor.java:44)
	at com.intellij.util.indexing.FileBasedIndexScanRunnableCollectorImpl.lambda$collectScanRootRunnables$5(FileBasedIndexScanRunnableCollectorImpl.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:970)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.util.indexing.FileBasedIndexScanRunnableCollectorImpl.collectScanRootRunnables(FileBasedIndexScanRunnableCollectorImpl.java:38)
	at com.intellij.util.indexing.FileBasedIndexImpl.collectScanRootRunnables(FileBasedIndexImpl.java:2334)
	at com.intellij.util.indexing.FileBasedIndexImpl.iterateIndexableFiles(FileBasedIndexImpl.java:2326)
	at com.intellij.util.indexing.FileBasedIndexImpl.projectIndexableFiles(FileBasedIndexImpl.java:1087)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:944)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:818)
	at com.intellij.psi.search.FileNameIndexServiceImpl.getFilesWithFileType(FileNameIndexServiceImpl.java:56)
	at com.intellij.psi.search.FileTypeIndex.getFiles(FileTypeIndex.java:41)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldFileService.findSkaffoldFiles(SkaffoldFileService.kt:79)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldConfigurationDetector$Companion.isSkaffoldConfigurationNeeded(SkaffoldConfigurationDetector.kt:68)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldConfigurationDetector.showPromptForSkaffoldConfigurations(SkaffoldConfigurationDetector.kt:130)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldConfigurationDetector.access$showPromptForSkaffoldConfigurations(SkaffoldConfigurationDetector.kt:50)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldConfigurationDetector$projectOpened$1.run(SkaffoldConfigurationDetector.kt:83)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:232)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:360)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$3(StartupManagerImpl.java:166)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:232)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$6(StartupManagerImpl.java:392)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:394)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:224)
	at com.intellij.ide.startup.impl.StartupManagerImpl.queueSmartModeActivity(StartupManagerImpl.java:166)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$400(StartupManagerImpl.java:48)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.lambda$run$0(StartupManagerImpl.java:196)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.run(StartupManagerImpl.java:196)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:232)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$6(StartupManagerImpl.java:392)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:394)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:224)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:184)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$7(ProjectManagerImpl.java:411)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at com.intellij.util.io.IOUtil.readUTFFast(IOUtil.java:131)
	at com.intellij.util.io.IOUtil.readUTF(IOUtil.java:85)
	at com.intellij.util.io.EnumeratorStringDescriptor.read(EnumeratorStringDescriptor.java:47)
	at com.intellij.util.io.EnumeratorStringDescriptor.read(EnumeratorStringDescriptor.java:27)
	at com.intellij.util.io.AppendableStorageBackedByResizableMappedFile.read(AppendableStorageBackedByResizableMappedFile.java:79)
	at com.intellij.util.io.PersistentEnumeratorBase.valueOf(PersistentEnumeratorBase.java:472)
	at com.intellij.util.io.PersistentBTreeEnumerator.valueOf(PersistentBTreeEnumerator.java:505)
	at com.intellij.util.io.PersistentEnumeratorBase.isKeyAtIndex(PersistentEnumeratorBase.java:406)
	at com.intellij.util.io.PersistentBTreeEnumerator.enumerateImpl(PersistentBTreeEnumerator.java:398)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:290)
	at com.intellij.util.io.PersistentEnumeratorBase.enumerate(PersistentEnumeratorBase.java:313)
	at com.intellij.util.io.PersistentEnumeratorDelegate.enumerate(PersistentEnumeratorDelegate.java:98)
	at com.intellij.util.io.PersistentStringEnumerator.enumerate(PersistentStringEnumerator.java:70)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.lambda$getNameId$21(FSRecords.java:1135)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readAndHandleErrors(FSRecords.java:934)
```

 IntelliJ IDEA
app.version.major
 2019
app.version.minor
 1.2
java.version
 1.8.0_202-release
os.name
 Linux
plugin.version
 19.5.1

**Comment by etanshaul** [comment] 2019-05-31 15:35
seems possibly related to other issues we noticed previously with the mechanism we are using for detecting skaffold.yaml. Added this to our next milestone to investigate this and the broader issue (to see if it makes sense to update how we detect `skaffold.yaml` files in general).

**Comment by etanshaul** [comment] 2019-06-10 14:12
@sageprice reassigning to you to distribute out our milestone issues.

**Comment by sageprice** [comment] 2019-06-10 18:37
I haven't had any luck reproducing this. The problem seems pretty internal, I'll post a question in the IntelliJ dev slack channel to see if I can get some help on it.

At this point we've gotten exactly one report for it, so if we don't get any feedback I'm inclined to close until we have either more traces or user guidance on how to trigger.

**Comment by etanshaul** [comment] 2019-06-10 18:42
sgtm. thanks for investigating.

**Comment by YannCebron** [comment] 2019-06-11 08:27
any chance there was an abrupt termination of IDE?

**Comment by sageprice** [comment] 2019-06-11 13:24
> any chance there was an abrupt termination of IDE?

Can't say for sure. The above stack trace and application/system info are all that was reported to us. Would abrupt termination be a potential cause or effect here?

**Comment by YannCebron** [comment] 2019-06-11 13:28
Yes, as in "most likely" (unless it can be reproduced in some way).

**Comment by sageprice** [comment] 2019-06-11 13:32
Actually wait, this report comes from an IDE dialog. So it is probably safe to assume the IDE had not crashed, otherwise the reporting system would have been unavailable (assuming crash means application stops completely).

Also, thanks for jumping in to help @YannCebron! Sorry we don't have more information.

**Comment by YannCebron** [comment] 2019-06-11 13:36
there _was_ an abrupt termination. as in "previous session" - this exception was catched on next attempt of startup with possibly broken cache files

**Comment by sageprice** [comment] 2019-06-11 14:02
Oh interesting. So if I'm following we have something like this:

1. IDE crashes (for reasons unknown)
1. Cache is left in a bad state due to crash
1. On resumption, we try to read a broken cache file and throw error

It's unclear to me what happens next. I'd assume the user could blow away the cache, re-build, and resume work without issue? And if this is what happened, it doesn't seem like there is much we can do without knowing why the IDE crashed in the first place. Does that make sense?

**Comment by YannCebron** [comment] 2019-06-11 14:07
Correct. Caches should/will be rebuilt when catching such state, thus everything should work again later. There's nothing your plugin can do about it really.

**Comment by sageprice** [comment] 2019-06-11 14:13
Understood. Given all that, I'm going to go ahead and close this issue since there isn't anything we can really do here. Thank you very much for your help!

**Closed by sageprice** 2019-06-11 14:13 UTC
Labels: Kubernetes
