### ISSUE TITLE
Unable to load library 'CoreFoundation'

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2808] opened 2020-08-18 15:15 UTC
It sounds like macos can't load a native library. Not sure if there is much we can do here.

```
java.lang.UnsatisfiedLinkError: Unable to load library 'CoreFoundation':
dlopen(libCoreFoundation.dylib, 9): image not found
dlopen(libCoreFoundation.dylib, 9): image not found
Native library (darwin/libCoreFoundation.dylib) not found in resource path
...
```

https://listnrcrash.corp.google.com/product/717949/report/1000000822887690848

**Comment by simonsickle** [comment] 2020-09-24 16:38
See https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes for details on this, specifically 

> New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

**Comment by etanshaul** [comment] 2020-09-24 17:41
interesting. thanks for the info @simonsickle 

from looking at the crash report it doesn't look like this is in our control (rather, caused by the intellij platform). Might be worth filing a report with them (I can do this).

**Comment by simonsickle** [comment] 2020-09-24 17:48
@etanshaul this was already fixed in 2020.2.1 it seems, note available builds and available in

https://youtrack.jetbrains.com/issue/IDEA-244962

**Comment by etanshaul** [comment] 2020-09-24 17:50
good find! I was just digging through youtrack to no avail. thanks again.

**Comment by 8secz-johndpope** [comment] 2020-12-11 17:04
I'm seeing this on Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 6
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
11.1 Beta (20C5061b)
will update OS.

**Comment by etanshaul** [comment] 2020-12-11 17:18
@8secz-johndpope interesting. I assume you are not using the Cloud Code plugin though (as we don't officially support Android Studio at the moment)?

**Comment by etanshaul** [comment] 2020-12-11 17:53
I'm going to mark this as closed @simonsickle because the platform fix by JB was made available in 202 and 203 builds. We'll reopen if we start to see this again.

**Closed by etanshaul** 2020-12-11 17:53 UTC
Labels: kind/bug, kind/crash-report, priority/p3

**Comment by guitorioadar** [comment] 2021-02-25 00:41
I am facing the same issue with android studio 4.1.2

Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true

**Comment by etanshaul** [comment] 2021-02-25 01:03
Hi @guitorioadar is the error you are seeing coming from the Cloud Code / Cloud Tools for Java plugin?

But regardless, once android studio picks up the changes from the core intellij platform, then this error should go away.

**Comment by shpetimselaci** [comment] 2021-04-11 18:43
I'm facing the same issue with Android Studio 4.1.2

Android Studio 4.1.3
Build #AI-201.8743.12.41.7199119, built on March 11, 2021
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true

MacBook Pro M1

Let me know if you need additional information.

**Comment by maxrks** [comment] 2021-04-15 11:40
**BigSur 11.2.3 and Android Studio 4.0.2**, every time when AS IDE open, there be a red error icon come up at the right-bottom corner, but the IDE work as normal... so let's make  a faker trick:

locate to `/Applications/Android Studio.app/Contents/bin`,  make a duplicate of `libnst64.dylib`  and rename the duplicate as `libCoreFoundation.dylib`

reopen the IDE, the error would be gone.

**Comment by maxrks** [comment] 2021-04-15 11:53
**BigSur 11.2.3 and Android Studio 4.0.2**, every time when AS IDE open, there be a red error icon come up at the right-bottom corner, but the IDE work as normal... so

locate to `/Applications/Android Studio.app/Contents/bin`,  make a duplicate of `libnst64.dylib`  and rename the duplicated as `libCoreFoundation.dylib`

reopen the IDE, the error would be gone.

**Comment by etanshaul** [comment] 2021-04-15 15:03
@maxrks thanks for the workaround! I haven't tested that myself, but as mentioned above, this error seems to be a common platform error coming from specific IntelliJ platform versions. Android Studio typically lags behind the latest IntelliJ version. Once the changes are incorporated from upstream, this issue should be resolved. Unfortunately there is nothing I'm aware of that Cloud Code can do here to assist.

**Comment by maxrks** [comment] 2021-04-15 15:54
@etanshaul fews days ago, I was still using **Catalina 10.15.7 + Android Studio 4.0.2**, there was no problem on the `libCoreFoundation.dylib`. After upgrade to BigSur, the issue came up. It could be a bug about IDE running on OS. I hesitated to update the AS to the latest stable version due to some plugins incompatible. Hope the trick help.

**Comment by alexbrinkman** [comment] 2021-04-29 17:28
I was having the same issue on BigSur 11.3 until I updated Android Studio to 4.1.3.  Now everything is working properly again.

**Comment by batthis** [comment] 2021-04-30 16:23
Check updates... emulator had an update. Worked fine after.
