### ISSUE TITLE
Cloud plugin prevents proper k8s/helm syntax highlighting and code complete

### ISSUE THREAD

**Issue by nyurik** [GoogleCloudPlatform/cloud-code-intellij#2874] opened 2021-01-20 23:27 UTC
When editing Kubernetes/Helm yaml files, this plugin takes over the syntax highlighting and all other functionality provided by the [kubernetes plugin](https://plugins.jetbrains.com/plugin/10485-kubernetes), without any way to disable it.  I found this setting, but it doesn't seem to have any effect (in Settings > Cloud Code > Kubernetes):
![image](https://user-images.githubusercontent.com/1641515/105253208-06d27f80-5b4d-11eb-97ef-ceb3f9c9d40d.png)

Note that this only occurs if [yaml-ansible-support](https://plugins.jetbrains.com/plugin/7792-yaml-ansible-support) is also enabled.

### Expected Behavior
![image](https://user-images.githubusercontent.com/1641515/105252664-e35b0500-5b4b-11eb-9d2a-0f8871aec9af.png)

note that helm params can auto-compute/expand:
![image](https://user-images.githubusercontent.com/1641515/105252681-eb1aa980-5b4b-11eb-8b7f-fa7f0b607cd4.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/1641515/105253009-9e839e00-5b4c-11eb-8c46-411e63592fdc.png)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): InteliJ IDEA Ultimate
- IDE version: 2020.3
- Cloud Code version (Settings > Plugins > Cloud Code): 21.1.1-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: yes
  - Version of the Cloud SDK:324.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): v1.17.2
- Operating System: Linux Mint 20.1

**Comment by nyurik** [comment] 2021-01-20 23:32
I think I found the culprit -- this occurs only if https://plugins.jetbrains.com/plugin/7792-yaml-ansible-support is also installed.

**Comment by matthewmichihara** [comment] 2021-01-21 15:37
Very strange, I'm able to reproduce this as well. I'm not sure what the root cause is, but a workaround to re-enable syntax highlighting might be to manually add `*.yaml` in this preferences screen:

![image](https://user-images.githubusercontent.com/79073/105373282-86576180-5bd4-11eb-8dd2-9ef3a38cc3f6.png)

Somehow `*.yaml` is being removed here with this combination of plugins.

**Comment by nyurik** [comment] 2021-01-21 16:13
@etanshaul yes, it seems that way. Only if both the ansible plugin and gcloud plugins are enabled, yaml breaks. I do not know which of the two plugins creates this issue, but I suspect it is gcloud because ansible is designed to always handle yaml, whereas gcloud tries to avoid yaml if disabled.

**Comment by matthewmichihara** [comment] 2021-01-21 18:23
From what I can tell, it doesn't look like the YAML/Ansible plugin is fully compatible with the YAML plugin (https://github.com/vermut/intellij-ansible/issues/67).

When I just have the YAML plugin and YAML/Ansible plugins installed, I see this in my event log asking me to choose which plugin I want to associate with the `*.yaml`, `*.yml` file types.

By default, IntelliJ seems to prefer the YAML plugin (as the event log messages show), but Cloud Code being installed seems to interfere with this.

**Comment by etanshaul** [comment] 2021-01-22 15:59
Hi @nyurik we found a fix and it will be available in the next (January) release - tentatively scheduled for next week.

**Comment by etanshaul** [comment] 2021-02-03 14:49
the fix was been released in version `21.2.1`.

**Closed by etanshaul** 2021-02-03 14:49 UTC
Labels: area/editing-support, area/lsp, fixed-in-next-release, kind/bug, priority/p3
