### ISSUE TITLE
Webstorm freezes when selecting a database

### ISSUE THREAD

**Issue by DiegoVillalobos-SB24** [GoogleCloudPlatform/cloud-code-intellij#3168] opened 2023-10-30 08:58 UTC
### Expected Behavior

After selecting a database in the sidebar, the IDE should not freeze when a file is edited.

### Actual Behavior

After selecting a database in the sidebar, the IDE freezes when editing any file.

### Additional Information

After clicking on a database to connect to, the connection is established in the IDE terminal, from there, if you edit any file in the project, the IDE will freeze from upwards of 30 seconds to a minute.

- IDE type (e.g. IntelliJ, Pycharm): Webstorm
- IDE version: WebStorm 2023.2.4
- Cloud Code version (Settings > Plugins > Cloud Code): 23.10.1
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: 452.0.1
- Operating System: Sonoma 14.0 - Apple M1 Pro 16GB

**Comment by ivanporty** [comment] 2023-10-30 15:50
Thanks for the report @DiegoVillalobos-SB24! Does it only happens when connection is active? Is there any specifics about a file being edited - its type, does it matter or affects the freeze somehow?

**Comment by ivanporty** [comment] 2023-10-30 15:55
It seems like we cannot reproduce easily. Could we take a look at IDE log file to look for any errors (idea.log, find using Help -> Show Log In Finder menu)

**Comment by ivanporty** [comment] 2023-12-07 00:05
Closing in favor of newer #3173

**Closed as completed by ivanporty** 2023-12-07 00:05 UTC
Labels: area/databases
