### ISSUE TITLE
List Google Source Repositories does not work

### ISSUE THREAD

**Issue by SandorSzalma1** [GoogleCloudPlatform/cloud-code-intellij#2568] opened 2019-05-22 15:38 UTC
- PyCharm 2019.1.2
- Cloud Code for IntelliJ version: v19.5.3
- OS: Windows 10

**What did you do?**
VCS\Check out from Version Control\Google Cloud

**What did you expect to see?**
The list of the google cloud source repositories

**What did you see instead?**
Error loading repositories

Google Cloud Code Plugin is configured, I can see the buckets in my projects.

But I cannot see my Source Repositories.

**Comment by etanshaul** [comment] 2019-05-22 16:09
Hi @SandorSzalma1 

Thanks for reporting and sorry you are running into trouble.

Just to confirm, when you go to the cloud console in your web browser, you see Cloud Source repositories for the cloud project?

Could you possibly provide a screenshot of the error you are seeing too (redacting and personal / project info from the screenshot)?

**Comment by SandorSzalma1** [comment] 2019-05-23 05:57
Hi @etanshaul 

Thanks for contacting me!

I can see the same repositories in the browser and with the google cloud sdk (gcloud source repos list), too.
I work behind a proxy with TLS-interception, so I added the issuer certificates of the proxy to the cacerts file used by the Java apps with PyCharm.
With the same project I can see the buckets with PyCharm/Cloud Code Plugin, too.

I have attached two screenshots.
![2019-05-23_075231](https://user-images.githubusercontent.com/47599005/58228910-681acd80-7d30-11e9-8e40-bb14445eed33.png)
![2019-05-23_075424](https://user-images.githubusercontent.com/47599005/58228921-71a43580-7d30-11e9-92ef-1240a45dbc25.png)

**Comment by cedricdv** [comment] 2019-10-09 13:04
Jup, experiencing exact same behaviour. However, I am able to just check out a repo outside of pycharm and then continue work with it inside pycharm. But I cannot list my project's repositories on google cloud.

**Comment by etanshaul** [comment] 2019-10-09 13:10
@cedricdv Thanks for bringing this back to our attention. We will investigate and adjust priority accordingly.

**Comment by etanshaul** [comment] 2019-10-09 15:56
Just a small update. We have identified the problem: we were using a no longer working service URL for the API calls to fetch the list of cloud source repos. A fix is going in now and will make it on the next release (likely around the last week of this month).

In the meantime I suggest checking out the repo via the command (apologies for the inconvenience). Once this fix is in, and if feeling adventurous, you could grab our [nightly](https://github.com/GoogleCloudPlatform/cloud-code-intellij#installation) release which will contain the fix (probably some time tomorrow).

**Comment by Portur** [comment] 2019-12-12 12:16
Same issue with IDEA.

Tried cloning the empty repo with gitbash but getting a `403`. 

This error and message is also received when adding the remote to git when pushing from local repo.

**Comment by Portur** [comment] 2019-12-12 12:24
I should also add I have no way of using gcloud source repos at this time, to and from the repo. **This is game-breaking for me and forces me to hold onto the machine that still works.**

`gcloud auth login` does not resolve this and application specific credential's seems to be deprecated once logged in.

**Comment by etanshaul** [comment] 2019-12-12 14:22
@Portur sorry for the troubles. I will look into this today. Could you provide some more details please:

- what version of cloud code are you using
- what version of the IDE 
- what OS
- to confirm - on the machine where the Cloud Code integration isn’t working - the command line isn’t working either?

**Comment by jmah-cc** [comment] 2020-06-11 16:26
The original issue was fixed. Please re-open if you're still running in to the additional issue mentioned towards the bottom of this ticket

**Comment by spwla-app** [comment] 2020-06-29 01:39
I'm facing the same problem, keep seeing the message "Error loading repositories" in Android Studio. 
Anyone knows the fix?

**Comment by etanshaul** [comment] 2020-06-29 02:17
@spwla-app thanks for the report. I’ve reopened this issue and we’ll investigate this on Monday. 

In the meantime, if this is blocking your workflow, perhaps you can try using the command line until we can report back. Here is the link to the QuickStart with some info on using gcloud: https://cloud.google.com/source-repositories/docs/quickstart

**Comment by spwla-app** [comment] 2020-06-29 11:15
followed the steps on the webpage, keep getting error message - 
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Do I need to make a repository called "hello-world" or "origin". Have tried both but didn't work

**Comment by etanshaul** [comment] 2020-06-29 14:46
hey @spwla-app, are you trying to push code to a new repository on Cloud Source Repos? Or do you have code hosted already that you are trying to clone?

I'm going to guess the former:

I'd follow these steps: https://cloud.google.com/source-repositories/docs/pushing-code-from-a-repository

There are a couple prerequisite steps:
1) Set up a local git repository on the project you are trying to push
2) Create a new empty Cloud Source Repos repository. See this: https://cloud.google.com/source-repositories/docs/creating-an-empty-repository

After those two steps you should be able to follow the guide above (selecting the `Cloud SDK` tab for the `gcloud` steps).

Let me know if this doesn't help or if you need any more details. Thanks.

**Comment by spwla-app** [comment] 2020-06-29 14:58
I'm using android studio to push code on google cloud repository. Blank
repo is already created but doesn't show up in android studio. I can see
the cloud project name appear correctly but android studio says error
retrieving repositories.

**Comment by etanshaul** [comment] 2020-06-29 14:59
> I'm using android studio to push code on google cloud repository. Blank
repo is already created but doesn't show up in android studio. I can see
the cloud project name appear correctly but android studio says error
retrieving repositories.

Yeah. I was just able to reproduce this as well. I'm going to investigate the fix. In the meantime, hopefully the [above steps](https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2568#issuecomment-651169277) (using the gcloud command line (instead of the Android Studio UI)) helps unblock you (although I know it is inconvenient :( ).

**Comment by etanshaul** [comment] 2020-06-29 16:12
@spwla-app small update:

I found the issue in the Android Studio plugin: essentially it is pointing to a deprecated Cloud Source Repository endpoint (used for fetching the CSR repos from your GCP project). This was fixed in Cloud Code (which is what this repository covers - IntelliJ, GoLand, etc. but not Android Studio) but wasn't carried over to Android Studio. The Android Studio plugin is now a separate product. 

I'll carry over the patch to Android Studio so that it is fixed in an upcoming release.

**Comment by etanshaul** [comment] 2020-06-29 19:03
@spwla-app the fix has been implemented. The target version of android studio with the fix will most likely be `4.2`, and you should be able to get your hands on it early with `4.2 canary 5` (currently we are on canary 2: https://developer.android.com/studio/preview).

Let me know if you have any questions. Thanks.

**Comment by etanshaul** [comment] 2020-06-29 19:07
I'm going to close this issue in the meantime because this is about the Android Studio plugin (a separate product), and because the fix is already in. 

Please feel free to re-open if you run into any more issues, or feel free to follow up with any questions and we're happy to help.

**Closed by etanshaul** 2020-06-29 19:07 UTC
Labels: area/cloud-repos, kind/user-reported, priority/p1
